### ISSUE TITLE
[Bug]: Don't delete torrents with "EXPECTED VALUE (LIST, DICT, INT OR STRING) IN BENCODED STRING" status

### ISSUE THREAD

**Issue by KnifeFed** [StuffAnThings/qbit_manage#102]
### Describe the Bug

The other day I had a bunch of "unregistered" torrents deleted. The status message was `EXPECTED VALUE (LIST, DICT, INT OR STRING) IN BENCODED STRING`. This was some temporary issue and it's [libtorrent](https://github.com/arvidn/libtorrent/blob/95afba30e9acfd8411076a0b05f7ca69bf33b9bb/include/libtorrent/bdecode.hpp#L129) that spits out that message. So, these torrents shouldn't be deleted, just tagged as "issue".

### Logs

-

### Installation

Docker

### Version Number

3.2.0

### What branch are you on?

master

**Comment by bobokun** [comment]
Can you share some logs of this happening? It shouldn't be deleting those based on the unregistered torrent logic.

**Comment by KnifeFed** [comment]
PM:d you.
