### ISSUE TITLE
[FR]: Ability to work on more than just 'Completed' torrents

### ISSUE THREAD

**Issue by MrMeeb** [StuffAnThings/qbit_manage#115]
### Is your feature request related to a problem? Please elaborate.

My setup requires occassional additions by means of blackhole, which I'd then like Radarr/Sonarr to automatically pick up and handle from there. QBittorrent allows for multiple blackholes with unique save paths, so auto-categorizing works well in this case, since *arrs automatically detect torrents with the category they use for QBittorrent. 

qbit_manage allows for auto-categorizing of torrents based off save path, but only acts on completed torrents. The *arrs only seem to import and manage in-progress torrents. Thus qbit_manage will auto-categorize the torrent as desired, but only after it is too late for the *arr to take over.

### Describe the solution you'd like

Allow qbit_manage to optionally action torrents that are not completed. This would be a config option, and could be either a true/false or allow further configuration of what types of torrents are actioned, e.g 'in-progress', 'paused', 'stalled', etc - I can see the code uses a filter to select torrents, so this could probably be expanded upon to support more granularity.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I have forked this repo and removed the 'completed' option from the filter, allowing qbit_manage to action in-progress torrents. This appears to work fine. However I would prefer it to be 'officially' supported if possible. 

### Who will this benefit?

- Me
- Users with a similar need to me
- Users who like to organise and auto-categorise torrents while they're in progress - they could use multiple different scrapers that add to different blackholes, or would like the option of being able to do so - there is an exiting [FR ](https://github.com/StuffAnThings/qbit_manage/issues/50)for categorisation by regex, but this could be an alternative 

### Additional Information

Thank you!

**Comment by Th3-DoC** [comment]
I'd love to see this feature as well! It was requested 2yrs ago so I won't hold my breath, lol. I also don't see why this shouldn't be an official feature, I'd even be willing to donate this early in the game if it was added, I only picked up qbit_manage today as a replacement for Tixati, which handles this feature nicely, as many trackers have banned it for some reason. Thanks for your time and I look forward to seeing this project's continued growth in the future.

**Comment by hacshacdgacs** [comment]
Given I opened up another feature request that got closed and pointed to this one as already being requested I also would like this

**Comment by Th3-DoC** [comment]
For those interested in having these and many other added features, until an official release, if any. I have created a fork that can be found at the top of the page under  "Existing Forks" called qbit_manage_mod that I will continue to update as qBm updates if these features are not made official. I have sent a pull request with hopes of it becoming official! but there is no guarantees :)

**Comment by TDWillingham** [comment]
I would like to add some support for this as well.  I cross-seed with public trackers and some torrents will just be stalled forever.  If we could add an option to delete torrents with the data if it has been stalled for x amount of time, that would be awesome.

**Comment by bakerboy448** [comment]
Please don't comment and hijack already closed/implemented feature requests
