### ISSUE TITLE
[FR]: Ignore unsupported qbittorrent client if newer 

### ISSUE THREAD

**Issue by firestrife23** [StuffAnThings/qbit_manage#117]
### Is your feature request related to a problem? Please elaborate.

I find it mildly infuriating because every time I upgraded qbittorrent client then qbitmanage goes into the loop and constantly spamming my discord via notifiarr non-stop about the unsupported error. I had to kill the qbitmanage container and cannot use it to manage qbittorrent until then.

### Describe the solution you'd like

version checking should be based on equal or greater than x.x.x to avoid this headache. Could at least warn the user about the untested version and may experience some issues during the start-up rather than going into the loop.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

n/a

### Who will this benefit?

Users that keep their containers up to date to stay ahead of security vulnerabilities.

**Comment by bakerboy448** [comment]
Given Qbit's devs frequently push never tested changes and undocumented breaking api changes with new versions - while not patching security flaws - this seems likely it will cause a lot more trouble than it's worth.

Every single Qbit 4.4.X release has been a buggy, broken, undocumented changes piece of shit so far.

**Comment by foux** [comment]
That's not possible, as it's a limitation of the upstream project, `qbittorrent-api` which limits the QBittorrent version

**Comment by firestrife23** [comment]
Disappointing to hear about undocumented breaking changes. Maybe at least make it less spammy, and shutdown after 5 failures instead of endless reboot?

**Comment by bobokun** [comment]
It actually should shut down immediately and not reboot. Is it rebooting for you because you have it restart automatically? Do you have `--restart unless-stopped` set in your docker-compose?

**Comment by firestrife23** [comment]
> It actually should shut down immediately and not reboot. Is it rebooting for you because you have it restart automatically? Do you have `--restart unless-stopped` set in your docker-compose?

Yep that's what I have, what should I change it to?

**Comment by bobokun** [comment]
> Disappointing to hear about undocumented breaking changes. Maybe at least make it less spammy, and shutdown after 5 failures instead of endless reboot?

If you don't want the container to keep doing the endless reboot then remove `--restart unless-stopped` from your docker-compose. That way it won't keep restarting.
