### ISSUE TITLE
[FR]: Pushover integration

### ISSUE THREAD

**Issue by snab43** [StuffAnThings/qbit_manage#131]
### Is your feature request related to a problem? Please elaborate.

Lack of notifications.

### Describe the solution you'd like

Support for [Pushover](https://pushover.net) as another option for notifications. There could be an optional variable for a Pushover API key, then the option to write "pushover" in the webhooks section of the config.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Notifiarr, Apprise, and Webhooks. But I'm too invested in Pushover which works with all my other software.

### Who will this benefit?

People who use Pushover.

**Comment by mouzzampk2014** [comment]
Just a thought, qbitmanage has apprise integration already and you can use apprise for pushover integration. That how I set it up. I hope this helps. 

But this solution is definitely just an alternative and not an answer to your feature request.

**Comment by bobokun** [comment]
Pushover is already covered through apprise so there isn't a need for a separate integration
