### ISSUE TITLE
[FR]: Multi qBittorrent container support

### ISSUE THREAD

**Issue by ahatdude** [StuffAnThings/qbit_manage#140]
### Is your feature request related to a problem? Please elaborate.

This is not a problem per se, there is a work around which is to just have as many qbmanage containers as I have qBittorrent.
It would be a qol addition to have all the processes within on single config in a single container.

### Describe the solution you'd like

In a perfect world, we'd simply have a config to which we'd add IPs of the qBittorrent containers themselves and configure them individually there.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

The current alternative that I'm using is to have multiple containers.

### Who will this benefit?

Anyone wanting to trim down on containers.

**Comment by bobokun** [comment]
This kind of resolves this problem. It allows you to load multiple configuration files in one container using a wildcard. for example if you want to load all the configuration files starting with config then you will pass `config*.yml` in `--config-file`.  The reason why I didn't go with a single config approach is that it keeps things cleaner when having multiple configuration files as the config could be different per qbt instance. This allows for more flexibility while also reducing the number of qbm containers to one.

**Comment by BaukeZwart** [comment]
Tried the above solution, renamed config.yml to config_1.yml. When I try to load config_1.yml with the wildcard solution, qbm starts with setting and using a default config.yml.
```today at 2:49:31 PM| Locating config...                                                                                 |
today at 2:49:31 PM| Using /config/config.yml as config```

**Comment by bobokun** [comment]
Are you on the latest develop version? When adding `config*.yml` you should see all the configs loaded at the beginning. If you enable debug you should see the config files that will be loaded looking something like this. 
![image](https://user-images.githubusercontent.com/12660469/184640140-45f0fb16-94cc-4fe2-b1cb-809a2ebe426d.png)

**Comment by BaukeZwart** [comment]
I'm using Hotio nightly image.
Probably not having the latest commit(s) then.

**Comment by mindset-tk** [comment]
Hi, I'm thinking i'd like to use this feature, but I need to know before I start - would this cause issues if my instances all look at the same set of folders? That is, say I have maxed out a qbittorrent client that downloads its files to /Downloads/Linux-isos so I spin up a second client that points to the same folder and create a second config.yml file for that client. Would "orphaned" files that are seen in one client but not the other be moved to the orphaned folder?

**Comment by bakerboy448** [comment]
Multiple qbit instances using the same torrent folder is not and cannot be supported. Files not used by torrents in that instance in the folder will be marked as orphaned

**Comment by mindset-tk** [comment]
No worries! I will rework my folder structure and qbit instancing so that each one only looks at specific folders and use the provided pattern filtering to work through this. Thank you!
