### ISSUE TITLE
[FR]: Allow users to run commands via config

### ISSUE THREAD

**Issue by bobokun** [StuffAnThings/qbit_manage#149]
### Is your feature request related to a problem? Please elaborate.

With the new feature added to develop to load multiple configs #140 , some users might not want to run the same commands for each config. This allows users to run commands depending on your config setup.

Context: https://discord.com/channels/764440599066574859/921548253948964904/1008836120475357248

### Describe the solution you'd like

Define commands inside config

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

NA

### Who will this benefit?

All users who want to run different commands with multiple configs

**Comment by bobokun** [comment]
You can now define certain run commands via config. @Drazzilb08
https://github.com/StuffAnThings/qbit_manage/blob/2e15e35ef5f8b7705407d223ed7ea157cdffdd87/config/config.yml.sample#L6-L17

**Comment by bobokun** [comment]
Please refer to https://github.com/StuffAnThings/qbit_manage/wiki/Commands for updated list of commands that can be run via config

**Comment by Drazzilb08** [comment]
This is perfect, currently running it live, No issues noted.

**Comment by mouzzampk2014** [comment]
Working fine here too. 

True/False are case sensitive?

Ta
