### ISSUE TITLE
[FR]: empty_after_x_days for orphaned data as well

### ISSUE THREAD

**Issue by quorn23** [StuffAnThings/qbit_manage#155]
### Is your feature request related to a problem? Please elaborate.

Without hard links the orphaned files are perfect to leave cross-seeds seed out and then it moves them into orphaned. But currently there is no system in place to clean those on a schedule.

### Describe the solution you'd like

Being able to configure `empty_after_x_days` in orphaned data just like in recycle bin.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

The behaviour could certainly be executed by a cron script, that checks the folder/dates (assuming the move to orphaned works the same as recycle bin in terms of time stamps of the files) As the management happens with qbit_manage it would be desired to have it all in one place.

### Who will this benefit?

Everyone that isn't able to use hard links and has the torrent client setup to only remove the torrent and not the files. This way the data stays until the cross-seeds are done. This way you avoid having a lot of errored out torrents on client restart.

**Comment by bobokun** [comment]
Please test this as it's not thoroughly tested
