### ISSUE TITLE
[Bug]:  Improve Ratio Support - Support Unlimited for Ratio or Time

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#158]
### Is your feature request related to a problem? Please elaborate.

currently if either ratio or time is -1 (unlimited) then no ratio is set

### Describe the solution you'd like

-1 of ratio or -1 of time should only be unlimited for that specific goal not both

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

work around by leaving the -1 value out of qbm config

### Who will this benefit?

all users who wish to seed for X time regardless of rato

**Comment by bobokun** [comment]
this needs a new config option/command? Also would this be a bug rather than FR?

**Comment by bakerboy448** [comment]
why would this need a new option or command?

Yes arguably a bug then.

From what I recall - setting -1 for ratio or time results in qbm setting no limit at all. 

what should be expected is the limit is set for the non-unlimited attribute.

![image](https://user-images.githubusercontent.com/55419169/201748127-e8d9dbc6-e0fb-4096-b1a3-f717ae033ec1.png)


e.g. if ratio is unlimited, then set and enable time
e.g. if time is unlimited, then set and enable ratio
e.g. if time and ratio are unlimited, then set no ratio.
