### ISSUE TITLE
[Bug]: keyError when trying to add noHL

### ISSUE THREAD

**Issue by eliotalanfoss** [StuffAnThings/qbit_manage#159]
### Describe the Bug

When trying to run the program, a bug occurs in which there is no 'content_path' key in the torrent variable.

I am not sure if this is an issue with this code, with qbittorrent-api, or with qbittorrent itself.  I added a print statement on line 327 of qbittorrent.py to print the torrent variable, and it indeed is missing the content_path and root_path entry, only save_path entry exists.

I am running qbittorrent locally using qbittorrent-nox.

### Config

```yaml
Not necessary I think
```

### Logs

https://gist.github.com/eliotalanfoss/d2a8afa8dfbe78c859af34908cc5f30a

### Installation

Local

### Version Number

3.2.6

### What branch are you on?

master

**Comment by bobokun** [comment]
Does this happen on one particular torrent or every torrent? In your qbitorrent webUI do you see the contents of the particular torrent when clicking the content button at the bottom of the UI? 
![image](https://user-images.githubusercontent.com/12660469/193377049-3c72a578-3828-4f7c-8467-1281bdbc5d25.png)

**Comment by eliotalanfoss** [comment]
I tried deleting the particular torrent in question and the error seemed to persist.  It seems that every torrent has this problem.

In the webUI I can see the contents under the content tab for all of my torrents (I think, I am not going to check every single one, but the contents do exist and qbittorrent knows where they are (presumably) for the specific torrent file that was erroring at least)

**Comment by bobokun** [comment]
That's weird, qbitorrent-api should have `content_path` with it. What version of qbittorrent are you running?

**Comment by eliotalanfoss** [comment]
qBittorrent v4.2.5

**Comment by bobokun** [comment]
It might be a qbittorrent-nox bug or qbittorrent-api, but I don't think this is a qbm issue as I'm just using the qbitorrent-api which should be returning the `content_path`

**Comment by bakerboy448** [comment]
4.2.5 => 4.3 is when the paths materially changed

That's why in fall 2020 \*arrs did not support 4.3 for a short time

**Comment by bakerboy448** [comment]
Sonarr ref https://github.com/Sonarr/Sonarr/pull/3346

**Comment by eliotalanfoss** [comment]
I upgraded to the newer qbittorrent-nox using the unofficial Debian repo listed on the qBittorrent GitHub wiki.  The qbittorrent version on the official stable Debian repos is the version I was running and is not compatible with qbit-manage!
