### ISSUE TITLE
[FR]: qBittorrent 4.4.5 Api - Update

### ISSUE THREAD

**Issue by seedboxer** [StuffAnThings/qbit_manage#160]
### Is your feature request related to a problem? Please elaborate.

qBittorrent is now using a new API that needs a rework, this has already been done on flood. 

Are there plans to update qbit manage?

### Describe the solution you'd like

API update

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

Downgrading

### Who will this benefit?

Everyone

### Additional Information

Looking if this update is in pipeline, thanks

**Comment by bobokun** [comment]
qbm doesn't communicate to qbittorrent directly. It uses [qbittorrent-api](https://qbittorrent-api.readthedocs.io/en/latest/) which already supports v4.4.5
