### ISSUE TITLE
[FR]: Clean up torrents based on disk space

### ISSUE THREAD

**Issue by StoneColeQ** [StuffAnThings/qbit_manage#163]
### Is your feature request related to a problem? Please elaborate.

To seed torrents as long as physically possible, torrents should be deleted only once low on space. Seed ratio and time either deletes while there is plenty of space or doesn't when there is no space.

### Describe the solution you'd like

Check if disk usage is below user defined amount. I wrote a completely separate script for myself and it works flawlessly. It would be nice for others to have it as well.

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

There are no alternatives.

### Who will this benefit?

Everyone who has ever used a torrent, not just qbit_manage users. Torrents will stay seeded until they can't.

### Additional Information

Here is my implementation. Use a while loop on is_storage_full(), deleting a torrent each iteration.

![Code Snippet](https://user-images.githubusercontent.com/23747563/196301805-d6b93f3f-4514-4eca-9588-06602fff8625.png)

**Comment by bobokun** [comment]
This seems like a good idea but outside the scope of qbm. If you want you can make a PR to develop branch and place the script into https://github.com/StuffAnThings/qbit_manage/tree/develop/scripts ! I'm sure others who have that use case would love to use the script too.

**Comment by StoneColeQ** [comment]
I'm using qbit_manage through docker. Would I use a command like docker exec to manually run the script while the container is running?

**Comment by bobokun** [comment]
No it's outside the scope of qbit_manage so you would still run it as a standalone script and execute it from a cron.
