### ISSUE TITLE
[FR]: Add optional ability to rem_orphaned to skip files until they are XX time old. 

### ISSUE THREAD

**Issue by bulfinch** [StuffAnThings/qbit_manage#166]
### Is your feature request related to a problem? Please elaborate.

I've run into a few cases where a torrent is downloaded consisting of zipped files. Unpackerr unzips the file, into the directory, and before it can be picked up by sonarr/radarr, it is moved as an orphaned file. 

### Describe the solution you'd like

Adding a minimum time before moving a file seen as orphaned could fix this. 

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Setting the time interval longer between runs would provide more time for the uncompressed file to be picked up by sonarr/radarr, but there's always the possibility of the problem happening. 

### Who will this benefit?

Users who use unpackerr or other extraction applications ot unzipp torrents with compressed files.

**Comment by bobokun** [comment]
Thoughts on having `minutes` be the time interval in the configuration for this?

**Comment by ethanopp** [comment]
I was about to open a seperate feature request but its somewhat related... I think this could make a lot of sense for rem_orphaned to skip certain categories as well.

For example, a pre-import category.

When using services like unpackerr, you can get stuck in endless loops where an extract occurs, sonarr has an issue importing (for any number of reasons, not preferred word upgrade etc), qbit manage thinks its an orphan so moves to orphan dir, then unpackerr extracts again and continues the loop.

Being able to just skip the orphaning of 'pre-import' category would solve this

**Comment by bobokun** [comment]
@ethanopp Using [exclude_patterns](https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#orphaned) should resolve the issue you're seeing.

**Comment by ethanopp** [comment]
@bobokun could you please elaborate on how that could be used?

The filename could be any <movie_name>.<extension>... the only way to identify it is if it has not yet been imported by the arr app where I am using per/post categories... to my knowledge the exclude_pattern is regex on the filename, not the category that file is tagged as in the arr/qbit apps

**Comment by bobokun** [comment]
Yes, just add the glob pattern of the pre-import category root folder and it'll exclude the category since it won't look at any files in the folder if the category

**Comment by ethanopp** [comment]
Ah duh... forgot parent dir was the name of the category... will try this thanks!

**Comment by ethanopp** [comment]
@bobokun sorry for tag again - updated this comment from earlier

Per guidance from the Trash guide community - I do not have separate directories for each category.. so I don't believe it is possible with regex

```
Downloads/
├─ sonarr/
├─ radarr/
├─ readarr/

```
![image](https://user-images.githubusercontent.com/11603814/202717715-10f3fd14-c651-4012-904a-bfc96cad3981.png)

![image](https://user-images.githubusercontent.com/11603814/202717768-1ef748ff-bd1d-4311-ba70-237c150fe608.png)

**Comment by bobokun** [comment]
In that case even qbm wouldn't be able to differentiate which files are orphan and which aren't because it checks the filesystem folders and compares it with the folders in qbt to determine which are not found there. My suggestion is to change the save path for sonarr-incomplete to a separate save path. It shouldn't have any negative impact on the *arrs by doing so as that's how I run my setup.

**Comment by ethanopp** [comment]
Oh interesting... Alright I'll give that a try.

Is this the correct pattern to exclude categories like 'radarr-incomplete', 'sonarr-incomplete' etc?

`"**/*-incomplete"`

**Comment by bobokun** [comment]
you might need to add `/**` at the end of the incomplete so it recursively excludes any folders.
You can test [here](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2F%2A%2A%2F%2A-incomplete%2F%2A%2A&matches=false&tests=%2Fdownloads%2Fsonarr-incomplete%2Fmoviename.mkv&tests=%2Fdownloads%2Fradarr-incomplete%2Fmoviefolder%2Fmoviename.mkv)

**Comment by ethanopp** [comment]
Awesome thanks!
