### ISSUE TITLE
[FR]: Option for mover script to move files that are between x and y days old

### ISSUE THREAD

**Issue by Davo1624** [StuffAnThings/qbit_manage#168]
### Is your feature request related to a problem? Please elaborate.

Currently when mover script is invoked it will move all files between 0 and the specified number of days. This does not allow for files that are less than the specified days to remain on cache.

### Describe the solution you'd like

Include an option to specify the minimum and maximum amount of time that should be considered for a file to be moved

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

None

### Who will this benefit?

Anyone who wants files to remain on cache for a specific duration

**Comment by bobokun** [comment]
so while I was working on this I realized I don't have control over what the mover is doing...so even though I pause torrents from two different dates, when I call mover it will still end up moving everything off cache :/ . I can definitely implement the pausing between specific days but I think in order for you to actually performing the moving you would need to configure [mover tuning plugin](https://forums.unraid.net/topic/70783-plugin-mover-tuning/)

**Comment by bobokun** [comment]
you can test the new script. It'll pause the torrents between those two dates you specify but you will still need to use mover tuning plugin to determine what files you want to move from cache. You will also need to change https://github.com/StuffAnThings/qbit_manage/blob/3bb3f092e1c21f1914cd4b9a76394c2be3fa1da8/scripts/mover.py#L63 to `  os.system('/usr/local/sbin/mover start')`
