### ISSUE TITLE
[Bug]: No Hardlinks is too restrictive causing false negatives

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#192]
### Describe the Bug

[Discord Convo](https://discord.com/channels/764440599066574859/921548253948964904/1049768789337718805)

No Hardlink logic currently requires only a single file in a torrent to be hardlinked to consider the torrent hardlinked.

For users that ran or run jdupes on a periodic basis this means some random tiny file make cause a large torrent to be kept when it should be removed.

```
bakerboy448@hetz-baker-2004:~$ ls -lha "/data/media/torrents/seeds-movies/Star.Wars.Episode.VI.Return.of.the.Jedi.1983.4K83.minimalNR.v1.6.1080p.35mm.DD2.0.x264-TN1/"
total 33G
drwxrwxr-x   4 bakerboy448 media   11 Mar 16  2022  .
drwxrwxr-x 259 bakerboy448 media  603 Dec  2 13:35  ..
-rw-rw-r--   1 bakerboy448 media  228 Mar 12  2022  00-Playlist.m3u
-rw-rw-r--   1 bakerboy448 media 1.1K Mar 12  2022  00-Playlist.xspf
-rw-rw-r--   2 bakerboy448 media 1.2M Mar 13  2022  01-TN1_LFL.mkv
-rw-rw-r--   1 bakerboy448 media 2.1M Mar 12  2022  02-ROTJ-BBFC.mkv
-rw-rw-r--   1 bakerboy448 media  34G Mar 12  2022  03-Return.of.the.Jedi.4K83.35mm.minimalNR.v1.6.1080p.mkv
-rw-rw-r--   1 bakerboy448 media 4.1M Mar 12  2022  03-Return.of.the.Jedi.4K83.35mm.minimalNR.v1.6.1080p.mkv_thumbs.jpg
-rw-rw-r--   1 bakerboy448 media  14K Mar 12  2022  03-Return.of.the.Jedi.4K83.35mm.minimalNR.v1.6.1080p.nfo
drwxrwxr-x   2 bakerboy448 media   10 Mar 12  2022 'Alternate Audio'
drwxrwxr-x   2 bakerboy448 media   66 Mar 12  2022 'SRT files 4K83 synced'
```

Solutions would be to look at the largest files and see if they're hardlinked

### Config

```yaml
N/A
```

### Logs

N/A

### Screenshots

N/A

### Installation

Nix

### Version Number

3.4.0

### What branch are you on?

develop

**Comment by bakerboy448** [comment]
Add per category list of user input file types for users to define what files to consider as hardlinks won't work by itself as with this reported example the problem file is an mkv

size will be a required route forward;  perhaps a combination of file type + size would be the best route?

![image](https://user-images.githubusercontent.com/55419169/206009338-4d9ef676-1f3b-400b-8d85-0ad333f4d041.png)

**Comment by bakerboy448** [comment]
```bash
find /data/media/torrents -type f -not -path "*/Scenes/*" -not -path "*/Behind The Scenes/*" -not -path "*/Trailers/*" -not -path "*/Featurettes/*" -not -path "*/Other/*" \( -iname \*.mp4 -o -iname \*.mkv ! -iname "*gag*" ! -iname "*blooper*" ! -iname "*Outtake*" ! -iname "*Sample*" \) -links 1 -print | sort
```

can be used to identify torrents that have video files with no hardlinks in the interim (excluding sample and similar ones)
Credits to Drazzlib and Davo on the script

**Comment by bobokun** [comment]
please test! :)

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/206081326-74294fc2-4f6c-48e6-acce-d0956c867b51.png)

Initial reporting looks like no known false positives / no obvious false negatives.
