### ISSUE TITLE
[FR]: Change Category based on Tracker URL

### ISSUE THREAD

**Issue by kosgitcat** [StuffAnThings/qbit_manage#200]
### Is your feature request related to a problem? Please elaborate.

I prefer to utilize the file directory structure of categories to keep certain trackers apart, rather than just using tags. Currently there is a way to update categories/locations and there is a way to update tags/trackers but there is no way to assign categories based on trackers.

### Describe the solution you'd like

Add an configuration option to allow torrents to have their categories automatically changed based on the tracker they connect to, like how the tag update on tracker function works.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

An alternative would be to automatically change categories based on tags. This would be an extra step in the flow, but the end result would be the same.

### Who will this benefit?

This would benefit anyone who prefers to, or makes large use of categories and would like more automated controls.

**Comment by imTHAI** [comment]
I'm looking forward for this feature too. 
I'd like to be able to drag the .torrent file inside the watch folder and qbt would do the magic. Currently, we have to set the category manually with each torrent we add.

**Comment by imTHAI** [comment]
@bobokun  you rock. Thank you
