### ISSUE TITLE
[FR]: Look in specified directory for hardlinks instead of checking link count

### ISSUE THREAD

**Issue by akesher123** [StuffAnThings/qbit_manage#208]
### Is your feature request related to a problem? Please elaborate.

It looks like the method qbitmanage uses to determine whether or not a file should be tagged/removed as no-hardlinks is to look and see if the link count is less than/equal to 1. I'm working on a PR for cross-seed right now to use hardlinking for cross seeds. This won't work well with qbm since those files will be hardlinked at least once more by cross seed, so it would never recognize cross-seeded files as needing removing. Most of the feedback I've recieved for the PR so far revolves around hardlinks as a wish as well as it being compatible with qbm.

### Describe the solution you'd like

Allow the user to specify some directory to look for hardlinks, naturally for most people the radarr/sonarr media folder. Check if the file is linked once. If it is, mark as noHL. If it is linked more than once, check if it is linked in the specified directory, if it isn't, mark noHL. Or modify the logic as you see fit.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I've considered coding things on the cross-seed side differently. In fact, the existing PR does not use hardlinks and thus would work well with that feature of qbm, but runs into forced rechecks. It also works in-place so categories folders can get messed up when searching for things in subdirectories.

It would be much easier on the cross-seed side of things to support this feature to make the two tools play nicely together. I think this is a useful feature in general as well.

### Who will this benefit?

Anyone that uses the new cross-seed PR along with radarr/sonarr and qbm can utilize this to simplify their workflow. If this feature is implemented, everything should work smoothly together including auto TMM related features and hardlink features.

**Comment by bobokun** [comment]
hmm, there isn't really an elegant solution as there isn't an easy way to find out where the hardlinks link to. You would have to loop through every file in your media library to get the inode of each file and compare that with the inode of the file in the torrents directory in order to determine if the link is in your media folder.

**Comment by bobokun** [comment]
closing in favor of #291
