### ISSUE TITLE
[FR]: Custom "noHL" Tag

### ISSUE THREAD

**Issue by CarlitoGil** [StuffAnThings/qbit_manage#210]
### Is your feature request related to a problem? Please elaborate.

The "noHL" tag sorts **between** other alphanumeric tags.

### Describe the solution you'd like

I would like the `noHL` tag to be customizable, like the `issue` tag with `tracker_error_tag`.
In my case it would be `(noHL)` so it sorts before other tags.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Renaming all other tags doesn't seem cleaner. There are fewer administrative tags such as `noHL`.

### Who will this benefit?

If you use tags for tracker names, cross-seed, etc., and sort by the Tags column you could control if all `noHL` are together, or if it sorts after the tracker names by using `~noHL~`.

**Comment by bobokun** [comment]
This has been added to develop branch. 
You can configure the custom tag through the new option `nohardlinks_tag` found in settings portion of the config.yml.

Please note you want to also adjust `ignoreTags_OnUpdate` and replace `noHL` with your custom tag.

https://github.com/StuffAnThings/qbit_manage/blob/d1c26fffa685a72bfc0916c7d1c300624b98246c/config/config.yml.sample#L25-L32

Please test and let me know if you encounter any issues. Thanks!
