### ISSUE TITLE
implement minimum seed time for tracker settings

### ISSUE THREAD

**Issue by 2fst4u** [StuffAnThings/qbit_manage#212]
### Is your feature request related to a problem? Please elaborate.

Currently only the `nohardlinks` values have a `min_seeding_time` option. When using values under the trackers settings this setting is absent.

### Describe the solution you'd like

Implement the `min_seeding_time` setting under tracker settings.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

None

### Who will this benefit?

This would allow seed time and ratio targets to be used on a per-ttacker basis, while still conforming to tracker minimum seed time rules where required.

If for example a tracker has a hard limit of 2 days minimum seed time regardless of ratio, but you also set a seed ratio of 2 and you reach this target under 2 days, the torrent will be deleted early, violating the rules of the tracker.

**Comment by bakerboy448** [comment]
Invalid; this already exists

tracker already supports this....it's even in the config file example

**Comment by 2fst4u** [comment]
You didn't read properly. I'm not asking for it under the no hardlink settings.

**Comment by bakerboy448** [comment]
It already exists under the tracker settings.

QBM logic wise it only comes into play for nohardlinks as that's the only time - remove unregistered notwithstanding - seeding torrents would or could be removed.

what do you want the setting to do...?

**Comment by 2fst4u** [comment]
> It already exists under the tracker settings....I don't understand what you're asking for as it literally already exists as a setting under trackers.
> 
> what I pasted was literally from the config file example and from the tracker section...no idea why you believe it is only under nohardlinks.
> 


What you quoted:

 "Will ensure that noHL torrents from this tracker are not deleted by cleanup variable if torrent has not yet met the minimum seeding time (min)."

Appears nowhere in the wiki. Wherever you've taken it from even specifically states "nohl" which is not what I'm asking.

I'm asking for this setting to be available while a torrent still has a hardlink.

**Comment by bakerboy448** [comment]
> I'm asking for this setting to be available while a torrent still has a hardlink.

1) again, it is clearly a per indexer setting.  I don't understand how you don't understand the config example file?
2) that setting has no impact on anything other than the nohardlink logic.... so again, what do you expect the setting to do?

**Comment by 2fst4u** [comment]
What are you taking this quote from? This is a screenshot of the tracker settings:

![Screenshot_20230126-070621.jpg](https://user-images.githubusercontent.com/15257926/214646451-17c3f4d1-18c3-4bee-b914-f891828d1983.jpg)

There is no minimum seed time value.

**Comment by 2fst4u** [comment]
![Screenshot_20230126-071109](https://user-images.githubusercontent.com/15257926/214647385-ebd99f49-200c-4f6f-be67-62771c8477ab.jpg)
Nor is it shown anywhere in the example config under trackers.

**Comment by bakerboy448** [comment]
Wiki is out of date.

look at the actual config file on the repo....which is what users would be editing.

**Comment by 2fst4u** [comment]
> Wiki is out of date.
> 
> https://github.com/StuffAnThings/qbit_manage/blob/192169d79fa8a993abaa4994d4a936fb579064d0/config/config.yml.sample#L73
> 
> look at the actual config file on the repo....which is what users would be editing.
> 


Then my issue pertains to updating the wiki then doesn't it? Regardless of the actual setting being implemented or not, resolving this requires a fix to files in this repo.

> 
> Again, what do you want this setting to do? Why are you continually ignoring this question?
> 
> the setting has nothing to do with anything except for blocking a torrent with nohardlinks from being removed until the min is met.

Asking why I want something and then literally describing the exact time it would be used helps no one. I want to use this setting _because_ I want to set seed targets while files are still hardlinked. Is that so outrageous?

**Comment by bakerboy448** [comment]
> I want to use this setting because I want to set seed targets while files are still hardlinked. Is that so outrageous?

That's not what you've asked for.
That setting has nothing to do with seed targets....that's the other seeding time and the ratio settings that are the seed.  IT ONLY EVER IS USED IF THE TORRENT IS NOHL, has met the seedgoals (carried over from indexer settings or overrode with nohardlink category settings) and has not yet met the min seed time.   Then it'll be held until that time is hit.
