### ISSUE TITLE
[FR]: Support for 4.5.2

### ISSUE THREAD

**Issue by totalhavoc** [StuffAnThings/qbit_manage#232]
### Is your feature request related to a problem? Please elaborate.

Error message that 4.5.2 is not compatible

### Describe the solution you'd like

Support for 4.5.2

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Only alternative is to downgrade. 

### Who will this benefit?

everyone that has updated to 4.5.2

**Comment by seedboxer** [comment]
Also waiting for this think 4.5 has api update.

**Comment by estenlund** [comment]
Yeah looks like qbittorrent-api needs to be 2023.2.43 to support 4.5.2. I'm running in docker so I will wait on a new docker image that includes it.

**Comment by totalhavoc** [comment]
I'm probably wrong but I think qbittorrent-api just needs to be updated in the requirements file to 2023.2.43?

**Comment by 2fst4u** [comment]
Due to security vulnerabilities in 4.5.0 and 4.5.1 I have a tracker that has blacklisted those versions so 4.5.2 support would be really awesome.

**Comment by bakerboy448** [comment]
already in dev https://github.com/StuffAnThings/qbit_manage/commit/983dbe3457613c8b428593059d691a8b213d68a3
