### ISSUE TITLE
Not logging all noHL tags for all categories in script log.

### ISSUE THREAD

**Issue by JonzaUK** [StuffAnThings/qbit_manage#24]
Hi Everyone,

Note I'm bad at explaining stuff so hope you understand...

I updated to the latest version with the noHL update, upon adding all my categories to the nohardlink section. I ran a dry run and noticed that only one category would get tagged e.g Movies... even though I had multiple category's setup... but upon removing the --dry-run parameter and letting it actually run it worked with all category's.

So it seems like the script is working but just not logging the activity for all category's

**Comment by bobokun** [comment]
Fixed in latest development
