### ISSUE TITLE
[FR]: config creates full path if it doesn't exist

### ISSUE THREAD

**Issue by jonoff** [StuffAnThings/qbit_manage#271]
### Is your feature request related to a problem? Please elaborate.

The recycle bin config variable is always treated as a subfolder of `remote_dir`, and when specifying a full path it is stripped to it's basename, which becomes the last folder of a full path:

https://github.com/StuffAnThings/qbit_manage/blob/30c3beae2df5df4ce687ac114041e0c4b7ece432/modules/config.py#L412

### Describe the solution you'd like

The example config and comment indiciate it's used an the full path
` # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin`

Instead of joining paths, just treat it as a full path when specified.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

The default may be a subfolder, but why limit it in this way?

### Who will this benefit?

Any custom configurations

**Comment by bobokun** [comment]
It's not limited. If you specify full path it should work. Did you test and verify it's not working with the full path?

**Comment by bobokun** [comment]
The code that you shared is only specifying the default recycle path and default orphaned path. Those are being used as default when the user does not specify. I just tested this and it's working correctly with specifying the exact path. It will use the default if the folder you specified does not exist or is not accessible. That's probably why you are seeing it use the default recycle directory.

**Comment by bobokun** [comment]
yeah I can add additional logs. In case you're wondering, the code that does the check to see if the folder exists is found here:
https://github.com/StuffAnThings/qbit_manage/blob/9e621e35d54ca9388e7779a24fed305daf36d286/modules/util.py#L181-L183

**Comment by bobokun** [comment]
> I'm also wondering what the reasoning is to override the default ".RecycleBin" to instead point to the `basename` of a specified path, if the full path is not accessible.

It's because of #77, Not everyone might want the name ".RecycleBin" as the foldername. Taking the basename will keep the folder name of your preferred RecycleBin that you define in your configuration and put it in your root directory if the location you specified cannot be found. 

What is currently set in your config.yml under directory?

**Comment by bobokun** [comment]
Can you test the new develop branch? It should create the Recycle Bin folder now for the path you specified.

**Comment by bobokun** [comment]
Yes, hotios nightly tag points to develop branch
