### ISSUE TITLE
[FR]: Change the logic of HardLinks detection to ignore hardlinks detected in the same root_dir

### ISSUE THREAD

**Issue by ColinHebert** [StuffAnThings/qbit_manage#291]
### Is your feature request related to a problem? Please elaborate.

Currently the logic for no_hl is based on the number of hardlinks in existence. If less than two hardlinks exist, the torrent will be tagged as `no_hl`.

This can be an issue if two torrents have different layouts (say `/torrents/myMovie/myMovie (2023).mkv` and `/torrents/myMovie (2023) - Special Edition.mkv` being the same file). In this case the two torrents would never be marked as no_hl as there is always more than a single hardlink (even though for the purpose of torrent management we'd consider that file as not hardlinked).

### Describe the solution you'd like

The logic for hardlink detection can be changed slightly.

Before going through the hardlinks, it should be possible to count the number of occurences of each inode in `root_dir`.
Traversing the entire folder is similar to the operation done when looking for orphaned files.

Then when looking up the number of hardlinks for each torrent, rather than applying the logic `if os.stat(file).st_nlink > 1`, it should be possible to change the logic to ` if os.stat(file).st_nlink - inodes_count[os.stat(file).st_ino] > 0:`, that would effectively update the logic.

Original logic:
> no_hl means there are no hard links to that file (at all)

Suggested logic:
> no_hl means that there are no hard links to that file outside of the folder qbitmanage already manages

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Alternatives have been suggested in the past: https://github.com/StuffAnThings/qbit_manage/issues/208
This approach is a bit "cleaner" as it doesn't require the introduction of new "knowledge" in qbitmanage, simply assuming that the existence of hardlinks outside of `root_dir` can do wonders.

### Who will this benefit?

With the new version of [cross-seed](https://github.com/cross-seed/cross-seed), "data-detected" torrents can be created via hardlinks, it will lead to an increase in cases of "torrents that people might expect to see as no_hl not being treated as such".

**Comment by bobokun** [comment]
Thank you for the suggestion and for coming up with this logic. I've been trying to think of a way of figuring this out without having to mount the media library in order to determine hardlinks. This method is a much better approach. I've pushed a change out to develop branch, feel free to test.
