### ISSUE TITLE
[Bug]: Force Auto Torrent Management won't run without commands 

### ISSUE THREAD

**Issue by ftc2** [StuffAnThings/qbit_manage#305]
### Describe the Bug

it seems reasonable to me to do `set_auto_management(True)` on every torrent if `settings["force_auto_tmm"] and not self.config.dry_run`

however, that doesn't happen if you don't run any commands. in fact, i think it only happens when you run _certain_ commands.

`force_auto_tmm` happens only in `update_cat()` and `get_torrent_info()`. the former obviously won't happen with no commands running, and the latter won't happen either because of this:

https://github.com/StuffAnThings/qbit_manage/blob/a1a67d2d6b142585dae9001b8ec960fc2d6e56f4/modules/qbittorrent.py#L86-L88

so really it seems to only do it on `update_cat()` or on these:

https://github.com/StuffAnThings/qbit_manage/blob/a1a67d2d6b142585dae9001b8ec960fc2d6e56f4/modules/qbittorrent.py#L28

notably, it also looks like the `tag_update` command will not actually trigger `force_auto_tmm` on its own.

to me, that behavior is unexpected.

consider a use case where someone just wants to use qbit_manage to force auto tmm on their torrents as a first step to correcting some issue and doesn't want to use the other features yet.

### Logs

https://example.com/not-relevant

### Installation

Docker

### Version Number

3.6.3

### What branch are you on?

master

**Comment by bakerboy448** [comment]
This doesn't make sense as a bug....if anything it's a feature request for an auto_TMM command.

If you've told the script to do run no commands - then it correctly does nothing.  

Nowhere does anything say or imply auto_TMM  does anything on its own. https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#settings  It's fairly implicitly clear that it applies to torrents QBm processes.

**Comment by ftc2** [comment]
haha :)

nowhere does it say auto tmm doesn't execute on its own. i thought it was unclear anyway and expected it to work with no commands after reading the docs. that's why i read the code to see what the problem was and filed it as a bug.

agree to disagree? lol

**Comment by ftc2** [comment]
also, if you're receptive to the idea (call it a FIX, FEAT, or whatever you like lol) but are busy, i could probably do a PR. lmk
