### ISSUE TITLE
[FR]: Torrent cleanup without NoHL tag

### ISSUE THREAD

**Issue by nodiaque** [StuffAnThings/qbit_manage#308]
### Is your feature request related to a problem? Please elaborate.

I don't use HardLink in my configuration, either Sonarr, Radarr, etc. The way I manage my download is everything in unraid is downloaded to a download disk and sonarr/radarr copy it into the unraid array. Thus, qbittorrent never downloads it to the real disk and I cannot use HL.

Because of that, I would like to be able to use the cleanup feature for max_seed, min_seed, max_ratio (Etc) but without having to tag all of my torrent to no_hl.

### Describe the solution you'd like

Another configuration to do the cleanup on category without using the no_hl tag

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Currently using the no_hl check to tag torrent, which result in all torrent being tagged

### Who will this benefit?

Everyone?

**Comment by bakerboy448** [comment]
Why can't you simply use the existing tracker seed goals and existing cleanup when they've hit their goal functionality?

**Comment by nodiaque** [comment]
How do you use it without the nohl tag? Cause I just tried to do it, but the config is under the nohl configuration thus if I don't enable the nohl, cleanup doesn't start

**Comment by bobokun** [comment]
related to #88
