### ISSUE TITLE
[FR] - Webhook Notification Support On Completed Run

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#31]
- Provide an option to configure a webhook to post end of `job` summary results to

@Drazzilb08 any ideas on what content?

@austinwbest - any thoughts (content/format/python libraries?), if added will naturally request it for Notifiarr ;)

**Comment by austinwbest** [comment]
Similar to PMM finished notifications. It shows what all was added, removed, how long it ran, etc..

I can add support for this, no biggie. Whatever hooks are sent I can make a way to handle them

**Comment by Drazzilb08** [comment]
I like this idea. Can do much the same thing as PMM. Torrents removed. NoHL torrents set. Ect.

**Comment by afraazali** [comment]
Would be nice if the payload follows the Apprise payload https://github.com/caronc/apprise-api#stateless-solution. Makes it easier for anyone using Apprise and docker.

**Comment by austinwbest** [comment]
Hopefully it is better than the bazarr implementation as that is shit. Can apprise even handle a full json payload of data or is it just a simple text & body thing like bazarr uses

**Comment by afraazali** [comment]
According to the docs:

```
Payload Parameters
📌 urls: One or more URLs identifying where the notification should be sent to. If this field isn't specified then it automatically assumes the settings.APPRISE_STATELESS_URLS value or APPRISE_STATELESS_URLS environment variable.
📌 body: Your message body. This is a required field.
📌 title: Optionally define a title to go along with the body.
📌 type: Defines the message type you want to send as. The valid options are info, success, warning, and failure. If no type is specified then info is the default value used.
📌 format: Optionally identify the text format of the data you're feeding Apprise. The valid options are text, markdown, html. The default value if nothing is specified is text.
```

**Comment by austinwbest** [comment]
Guess quantity over quality wins that one. I would offer 2 options then, one for shit text services and json payloads for those who want notifications that look nice

**Comment by bobokun** [comment]
Sure, I'll try to leave options open for the user to decide.

**Comment by austinwbest** [comment]
> Sure, I'll try to leave options open for the user to decide. 

Quit taking about it and get on it! I'm over here waiting on you to send a payload 🤣

**Comment by bobokun** [comment]
I've been busy with work 😅 maybe I'll have more time next week to start on it. I want to revamp the current code to use classes as well, I'm not too experienced in OOP so I want to use this opportunity to learn as well

**Comment by bobokun** [comment]
@afraazali can you please test the apprise integration in the develop branch?

**Comment by afraazali** [comment]
> @afraazali can you please test the apprise integration in the develop branch? Instructions can be found on the [wiki](https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#apprise) or checking out the new [config.yml.sample](https://github.com/StuffAnThings/qbit_manage/blob/a7b20bf6a4a949eb04e8cd2ce918c28c4427ba15/config/config.yml.sample#L131)

Will do it later tonight. I didn’t realize you were doing an apprise integration. I setup a custom fastapi app to handle webhooks in the mean time.

**Comment by bobokun** [comment]
You will still need to set up [Apprise-API](https://github.com/caronc/apprise-api) separately in order to use this integration.

**Comment by afraazali** [comment]
Yup! I have it all set up. I was using it with cross seed. It was working. I’ve disabled it now since this project does notifications as well. I’ll report my findings after a few runs.

**Comment by afraazali** [comment]
@bobokun `run_start` and `run_end` are working as expected. I'll need to test for a little longer to see if the `function` webhooks work.

Thank you again for integrating with the apprise API.

**Comment by afraazali** [comment]
@bobokun,

I'm getting an error with latest develop, https://0bin.net/paste/IOuiCQYb#JrcwKx0G7lT1W2wajUH3tRJCVNs0Ihi+K6lIwmTxfsl

**Comment by bobokun** [comment]
Fixed in latest develop. Sorry I screwed up the config check, you'll need to redo your config for the webhooks section since that got erased.

**Comment by afraazali** [comment]
Great! I'll continue to test. Will let you know if I come across any other issues. Thank you.

**Comment by afraazali** [comment]
@bobokun 

getting the same error in the “checking paused torrents” routine

**Comment by bobokun** [comment]
hm I can't seem to replicate...it works fine for me. Can you paste your `webhooks` part in your config?

**Comment by afraazali** [comment]
Working now. Thank you!
