### ISSUE TITLE
[FR]: Add minimum seeders

### ISSUE THREAD

**Issue by Mavyre** [StuffAnThings/qbit_manage#321]
### Is your feature request related to a problem? Please elaborate.

It's always annoying when there are no more seeders on a torrent

### Describe the solution you'd like

We should be able to add a minimum seeders condition before cleanup. This would allow torrent not to die if we're the last and only seeder, for instance.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Tried to add a tag that is ignored by the cleanup funcion. Needs manual intervention.

### Who will this benefit?

Allows users to be sharing more fairly the torrents on some private trackers

**Comment by bobokun** [comment]
new config `min_num_seeds` under share_limits has been added, please test and let me know if you find any bugs

**Comment by Mavyre** [comment]
Do you have a docker image which I could test against?

**Comment by bobokun** [comment]
Yes you can test using the latest develop branch. `bobokun/qbit_manage:develop`
