### ISSUE TITLE
[FR]: Increase API timeout

### ISSUE THREAD

**Issue by BaukeZwart** [StuffAnThings/qbit_manage#343]
### Is your feature request related to a problem? Please elaborate.

don't know if it is in your control or hard coded in the qbit API but is it possible to increase the timeout.
When my qbit instances reach around 10K torrents, I noticed that qbm often fails to connect due to API errors.
Now during the summer months with fewer releases it's less of an issue, but starting September it will be an issue again to keep the total number of torrent well below 10K.

Discord discussion
https://discord.com/channels/764440599066574859/921548253948964904/1121132898838380626
https://discord.com/channels/764440599066574859/921548253948964904/1121133384488456242

### Describe the solution you'd like

If possible, make the timeout configurable or increase it

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Keep the number of torrents well below 10K

### Who will this benefit?

everyone with a large number of torrents

**Comment by bakerboy448** [comment]
looks like just need to update https://github.com/StuffAnThings/qbit_manage/blob/ee871b4f928ec1bab2e7940a01a1d1e1e2a5883c/modules/qbittorrent.py#L198

based on qbit api
https://qbittorrent-api.readthedocs.io/en/latest/behavior%26configuration.html#requests-configuration
