### ISSUE TITLE
[FR]: Sorting .torrent files

### ISSUE THREAD

**Issue by LoserForever88** [StuffAnThings/qbit_manage#349]
### Is your feature request related to a problem? Please elaborate.

**Feature 1 :　Automatically copy .torrent files to the downloading location, places it together among other files getting downloaded**

Since it is about qbit manage, I wonder if this feature can be added.  This feature had been requested for multiple times in other places so I'm posting the links below instead of repeating the details.   

Issue create in 2017 but QB official doesn't bother to change anything, note the temp solution at the end: https://github.com/qbittorrent/qBittorrent/issues/7999

https://www.reddit.com/r/qBittorrent/comments/lh5idx/automatically_save_torrentmagnet_in_same_folder/

**Feature 2: sort" .torrent files by tracker?**

Instead of having a huge pile of torrents in one single folder, it would be nice if .torrent files can be sorted/copied into folders based on their respective trackers as well: https://superuser.com/questions/894133/how-to-sort-torrent-files-by-tracker

### Describe the solution you'd like

See above.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

I'm not sure about this

### Who will this benefit?

People have requested this before.

**Comment by bakerboy448** [comment]
> Instead of having a huge pile of torrents in one single folder, it would be nice if .torrent files can be sorted/copied into folders based on their respective trackers as well:

Outside of scope. Perhaps Qbit Tools
Or simply parsing the .torrents can help with this.

> Feature 1 :　Automatically copy .torrent files to the downloading location, places it together among other files getting downloaded

what use case and benefits does this provide? What problem does it solve?

**Comment by bobokun** [comment]
out of scope

**Comment by GoogleBeEvil** [comment]
> out of scope
 I think it is useful



https://github.com/qbittorrent/qBittorrent/issues/7999#issuecomment-350982065
https://github.com/qbittorrent/qBittorrent/issues/7999#issuecomment-350106343
