### ISSUE TITLE
[FR]: Support version 4.5.4

### ISSUE THREAD

**Issue by b0ril** [StuffAnThings/qbit_manage#351]
### Is your feature request related to a problem? Please elaborate.

Qbittorrent Error: qbit_manage is only compatible with v4.5.3 or lower. You are currently on v4.5.4. |
| Please downgrade your qBittorrent version to v4.5.3 to use qbit_manage.                            |

### Describe the solution you'd like

Can we have support of latest Qbittorrent 4.5.4 ?

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

N/A

### Who will this benefit?

everyone

**Comment by bakerboy448** [comment]
Already in develop and already can be bypassed with a flag on master. https://github.com/StuffAnThings/qbit_manage/commit/e738dff8811978c69c5214900ebf715258e41873

**Comment by bobokun** [comment]
This is already in master

**Comment by b0ril** [comment]
ok but it is not part of the latest docker image :( 

|====================================================================================================|
|                           _     _ _                                                                |
|                          | |   (_) |                                                               |
|                      __ _| |__  _| |_   _ __ ___   __ _ _ __   __ _  __ _  ___                     |
|                     / _` | '_ \| | __| | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \                    |
|                    | (_| | |_) | | |_  | | | | | | (_| | | | | (_| | (_| |  __/                    |
|                     \__, |_.__/|_|\__| |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|                    |
|                        | |         ______                            __/ |                         |
|                        |_|        |______|                          |___/                          |
|     Version: 4.0.1 (Docker)                                                                        |
|     Newest Version: 4.0.2                                                                          |
|     Platform: Linux-5.13.x-x86_64-with-glibc2.28                                                   |
|     Scheduled Mode: Running every 30 Minutes.                                                      |
|====================================================================================================|
|                                            Starting Run                                            |
|====================================================================================================|
| Locating config...                                                                                 |
| Using /config/config.yml as config                                                                 |
| Commands found in config.yml, ignoring env variables and using config commands instead.            |
| Connecting to Qbittorrent...                                                                       |
| Qbittorrent Error: qbit_manage is only compatible with v4.5.3 or lower. You are currently on v4.5.4. |
| Please downgrade your qBittorrent version to v4.5.3 to use qbit_manage.
