### ISSUE TITLE
[FR]: Add a time_inactive to the share_limits

### ISSUE THREAD

**Issue by AN1MATEK** [StuffAnThings/qbit_manage#353]
### Is your feature request related to a problem? Please elaborate.

Sometimes I wouldn't like to stop a torrent if it actively seeding everyday. With this option, I could say if a torrent has reached its seeding goals but people are still downloading, it should be kept online. It helps people and helps to maintain a good ratio.

### Describe the solution you'd like

Another flag option in `share_limits` that will keep the torrent online if there was activity in the last X minutes.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I currently use `autoremove-torrents` to achieve this functionality. But `qbit_manage` has added more granular control for the seeding times, almost rendering the former useless. For me personally, this issue is holding me back.

Example of a config in `autoremove-torrents`:

`remove: seeding_time > 259200 AND last_activity > 259200`

### Who will this benefit?

People who care about seeding and people downloading the torrents. Also some niche group that uses `autoremove-torrents` maybe? I don't know about that! :)

**Comment by austinwbest** [comment]
Been waiting on this one for a year or two @bobokun lol
