### ISSUE TITLE
[FR]: Delete Cross-Seeded torrents when a torrent is deleted for being unregistered

### ISSUE THREAD

**Issue by balpokey** [StuffAnThings/qbit_manage#354]
### Is your feature request related to a problem? Please elaborate.

Setup is I have a torrent downloaded, let's say through Radarr, and I have multiple other torrents being cross-seeded from that one. Right now if that torrent downloaded from Radarr gets autodeleted because the tracker unregisters/deletes it, the torrents that are being cross-seeded remain in the qBit client. This will in turn use more storage and can be harder to track when you have duplicate of the same movie in your client (because cross-seeded torrents do not get a noHL tag), especially if you have 1000+ torrents in your client.

### Describe the solution you'd like

When a torrent is auto deleted due to being unregistered on the tracker, also auto delete any matching cross-seeded torrents. One solution would be to check for matching torrents that have the cross-seed tag and delete them as well.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

When deleting torrents for being unregistered if they do not contain the cross-seed tag, also delete the contents, so the cross-seeded torrents will error out and will be easier to find to delete.

### Who will this benefit?

I'm not sure what portion of users cross-seed.

**Comment by balpokey** [comment]
Config option and Command option can be had or not. Up to you as the developer

**Comment by bakerboy448** [comment]
If your setup supports hardlinks theres 0 duplicate space....? I don't see the issue this solves.

**Comment by balpokey** [comment]
The duplicates would come from let's say Raddar add MovieA-Group1 to my client. Then cross-seed script adds 5 cross-seeds for MovieA-Group1. So now I have 6 torrents, and you're right, no duplicate space is being used at this time. But then later MovieA-Group1 was trumped by MovieA-Group2 by that same tracker. Radarr notices there is a new update to MovieA because Group2's upload has a higher custom format number and add that to the client, and the tracker unregisters/deletes MovieA-Group1. qBit-manage will auto delete the original download for MovieA-Group1, but the cross-seeds for that torrent will remain (which means the content would remain on the drive), while I also have MovieA-Group2 downloaded as well. So I would have 2 copies of MovieA on my drive, one from Group1 (because of the cross-seed still in the client) and the new download from Group2.

**Comment by bakerboy448** [comment]
Simply include cross-seed's cats/tags in the noHL logic and there's no issue to resolve.

Your request was for unregistered but now you're saying that they're actually noHL....there's no functionality to add here?

There's no reason to remove cross-seeding torrents that are still hardlinked as there's nothing at all to gain from removing those. 

@bobokun feel free to reopen, but I don't see the benefit of the functionality to add here that would support any net new beneficial use.
