### ISSUE TITLE
[FR]: better exception logging

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#356]
### Is your feature request related to a problem? Please elaborate.

When unable to connect one must use debug to get the details. Let's make debugging easier and throw the exception and details with the error 

### Describe the solution you'd like

Above

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

N/a

### Who will this benefit?

Support and users

**Comment by bobokun** [comment]
even without debugging turned on, the logs should say the reason why:
https://github.com/StuffAnThings/qbit_manage/blob/master/modules/qbittorrent.py#L74-L85
