### ISSUE TITLE
[FR]: Create option for cleanup without deleting underlying files

### ISSUE THREAD

**Issue by datcactus** [StuffAnThings/qbit_manage#358]
### Is your feature request related to a problem? Please elaborate.

There are times when I'd like to remove a torrent from qBittorrent without actually deleting the underlying files. An example would be when I have multiple torrents running that point to a single file directory, but I have shorter seeding times defined for some trackers than others. If I enable the current cleanup implementation (which deletes the torrent files as well as the torrent), I run into the issue where the torrents I'd prefer to keep seeding longer have the files deleted from underneath them. If I keep cleanup disabled, the torrents never get cleaned up unless I do it manually and the remaining files eventually picked up by the remove_orphan function.

### Describe the solution you'd like

Create a cleanup config option that doesn't force file deletion and can be placed into the config file the same way as the current cleanup function can. Alternatively, implement it as a command line command/docker environment variable to change the behavior of cleanup. The current one implements delete_files=True but the torrents_delete function supports (and defaults to) delete_files=False.

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

N/A, solution section covers current idea.

### Who will this benefit?

Users who want torrents cleaned up from the webUI once they've met seeding requirements, but preserve the torrent files in the event that other torrents with longer seed times may be using them.

**Comment by bakerboy448** [comment]
This already exists.  QBM will not delete data if torrents are already using it.
