### ISSUE TITLE
[Bug]: qBit Manage can delete shared files during cleanup for torrents with different names

### ISSUE THREAD

**Issue by datcactus** [StuffAnThings/qbit_manage#359]
### Describe the Bug

The current logic for torrent cleanup makes the assumption that torrents that point to the same file(s) should have the same name. This is not always the case when torrents are injected via cross-seed. As an example, it's not uncommon to see something with a torrent_name on one tracker and torrent_name.mkv on another tracker. As such, when the cleanup process goes to check the count of torrents by name it will not find deviations like these and can delete files that are actually still in use.

Example:
- Torrent named 'BLEACH.S17E14.THE.LAST.9DAYS.1080p.AMZN.WEB-DL.DDP2.0.H.264-APEX' fetched
- Cross-seed found and injected two additional torrents named 'BLEACH.S17E14.THE.LAST.9DAYS.1080p.AMZN.WEB-DL.DDP2.0.H.264-APEX.mkv' that had the same file structure, so at this point all 3 torrents are pointing to the same underlying file
- Seed ratio requirement for 'BLEACH.S17E14.THE.LAST.9DAYS.1080p.AMZN.WEB-DL.DDP2.0.H.264-APEX' was met and as such it was deleted via the cleanup script since it was the only torrent in the torrent list with this name
- Cross-seed injected torrents with .mkv in their name are now broken as a result

### Logs

https://gist.github.com/datcactus/daac41f2d8365a02e673e4dc670f64f8

### Installation

Docker

### Version Number

4.0.2

### What branch are you on?

master

**Comment by bakerboy448** [comment]
@bobokun do we compare save paths instead?

or can we compare file contents

**Comment by Quafley** [comment]
Hello,

@bobokun When will this issue be addressed? Files of mine have been getting deleted consistently. I can't configure anything differently, so I am simply accepting the loss at the moment. Would be nice if there would be an ETA as I deem this a pretty serious issue myself.

**Comment by Quafley** [comment]
I personally believe the error to be in this function:

https://github.com/StuffAnThings/qbit_manage/blob/db5e881581ae4a8677961adf0b1dc043df15f114/modules/qbittorrent.py#L96C10-L96C10 

Where this might ultimately cause the issue:
https://github.com/StuffAnThings/qbit_manage/blob/db5e881581ae4a8677961adf0b1dc043df15f114/modules/qbittorrent.py#L196

I do not, however, have a fix.

**Comment by bobokun** [comment]
Hi can you please test the latest develop version and let me know if you still have this problem? Thanks!

**Comment by datcactus** [comment]
Reached out via Discord but while this solves the issue with the originally reported torrent it does not resolve the issue with other torrents that have significantly different naming conventions for the torrent/release name despite still having the same underlying files.

Examples from a couple of trackers:
BLU/BHD: 'Ninja.Kamui.S01E01.1080p.HMAX.WEB-DL.DD2.0.H.264-VARYG.mkv' is both the release name and filename
Nyaa: 'Ninja Kamui S01E01 1080p HMAX WEB-DL DD2.0 H 264-VARYG (Dual-Audio, Multi-Subs)' is the release name via magnet

The remove_extension function that was added will help in situations where the only difference in release names is an extension, but a better solution to this problem would be to create a mapping of torrent names/hashes to the files associated with them and use that as a comparison point when running the deletion logic. qbittorrent-api provides https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_files that can be used as a way to gather the files, and a list of dictionaries (or a nested dictionary) could be used to store the data to later iterate over.

**Comment by bobokun** [comment]
I've reverted the change for now to remove the extension until a proper fix

**Comment by bobokun** [comment]
@datcactus , can you please test again. The new logic uses save_files to determine cross-seeds so it should be more accurate than using names
