### ISSUE TITLE
[Docs]: Docker doc missing QBT_SHARE_LIMITS

### ISSUE THREAD

**Issue by Flameeeeee** [StuffAnThings/qbit_manage#364]
### What is the improvement or update you wish to see?

I would like to have this env var documented like the other ones :) 

### Is there any context that might help us understand?

Hi, I was looking at the configuration options for docker using env vars and saw that there was no entry in the doc to enable share_limits handling through env vars. 
After looking at the code I saw that it is integrated: https://github.com/StuffAnThings/qbit_manage/blob/master/qbit_manage.py#L258C25-L258C41

### Does the docs page already exist? Please link to it.

https://github.com/StuffAnThings/qbit_manage/wiki/Docker-Installation

**Comment by bobokun** [comment]
done
