### ISSUE TITLE
[FR]: Change category based on seeding time

### ISSUE THREAD

**Issue by crahzee** [StuffAnThings/qbit_manage#366]
### Is your feature request related to a problem? Please elaborate.

I'd like to be able to move torrents from my SSD to HDD based on seeding time to keep space on SSD for new torrents. I prefer using SSD for downloading to allow myself to start uploading faster.

### Describe the solution you'd like

Add an option to change category based on seeding time.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I attempted to use keep incomplete torrents in a separate directory (on SSD) but once the download completes it takes a while to move to the HDD and it interrupts upload activity on new torrents.

### Who will this benefit?

Users that like to use SSD for downloading and HDD for long term seeding or users that like to race.

**Comment by bakerboy448** [comment]
Why not just use incomplete folder on SSD; complete folders/cats on HDD, which would facilitate hardlinks as well; and then once read from HDD it'd likely be kept in RAM as far as seeding goes

**Comment by jamiebrand** [comment]
+1 on this... a feature I would find most useful! Any plans to implement?

Thanks a lot!

**Comment by bakerboy448** [comment]
@crahzee - https://github.com/StuffAnThings/qbit_manage/issues/366#issuecomment-1661144981

**Comment by crahzee** [comment]
Thanks. I ended up just doing incomplete on SSD. Works well for multiple smaller torrents.
