### ISSUE TITLE
[Bug]: Support qbit 4.5.5

### ISSUE THREAD

**Issue by d3mystified** [StuffAnThings/qbit_manage#377]
### Describe the Bug

```
| Qbittorrent Error: qbit_manage is only compatible with v4.5.4 or lower. You are currently on v4.5.5. |
| Please downgrade your qBittorrent version to v4.5.4 to use qbit_manage.                            |
```

### Logs

N/A

### Installation

Unraid

### Version Number

4.0.3

### What branch are you on?

master

**Comment by stevezau** [comment]
Hey Guys, is there a plan to support 4.5.5 or should I downgrade?

**Comment by bobokun** [comment]
Once [qbittorrent-api](https://github.com/rmartin16/qbittorrent-api) is updated to support 4.5.5 then it will be supported.

**Comment by alex036** [comment]
Looks like the check needs to be updated so we can use this with 4.5.5 now?

**Comment by bakerboy448** [comment]
There's no check to update; it's based on qbittorrent-api which has ready been bumped in develop, as the tag notes
