### ISSUE TITLE
[FR]: Add an option to limit the speed of downloads to the "share_limits" variable

### ISSUE THREAD

**Issue by Antorell** [StuffAnThings/qbit_manage#415]
### Is your feature request related to a problem? Please elaborate.

The `share_limits` variable has a setting to limit the speed of upload (`limit_upload_speed`) but misses an option to limit the speed of downloads. 
This setting would be useful to limit the download speed of public torrent to avoid overloading the bandwidth while downloading from a public tracker. 

### Describe the solution you'd like

Add the [download_limit](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html) API feature to the `share_limits` variable. 

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

none

### Who will this benefit?

People downloading from private as well as public tracker who wish to set tighter limits to public trackers.

**Comment by bakerboy448** [comment]
QBm only operates on completed torrents so this is moot

**Comment by Antorell** [comment]
I'm still using Qbittorrent 4.3.9 and I didn't realize qbit_manage had a lock to only work with "completed" torrent. I was thinking to try Qbittorrent 4.5.x as it has an option to run an external program when a torrent is added to limit public torrents. Is there any chance the `share_limts` behavior will ever be changed to works when a torrent is added?

It's all down to this line from what I could see:
https://github.com/StuffAnThings/qbit_manage/blob/db5e881581ae4a8677961adf0b1dc043df15f114/modules/core/share_limits.py#L40

changing it to 
        `torrent_list = self.qbt.get_torrents({"status_filter": "completed"} and {"status_filter": "downloading"})`
or
        `torrent_list = self.qbt.get_torrents({"status_filter": "completed"} and {"status_filter": "paused"} and {"status_filter": "downloading"})`
or 
        `torrent_list = self.qbt.get_torrents({"status_filter": "all"})`
With the changes, Share_limits get set when a torrent is added (at least --run from bash command line, I don't have qbittorrent 4.5.x installed yet)

> |============================= Updating Share Limits based on priority ==============================|
> | Assigning torrents to share limit groups...                                                        |
> |===================== Updating Share Limits for [Group default] [Priority 999] =====================|
> |    Torrent Name: Linux-Image-nogroup                               |
> |         Tracker:                                          |
> |         Added Tag: ~share_limit_999.default                                                        |
> |     Share Limit: Max Ratio = 1.0, Max Seed Time = 60 min                                           |
> | Webhook attribute set to notifiarr but notifiarr attribute is not configured.                      |
> |====================================================================================================|
> |                                            Finished Run                                            |
> |                                      Total Torrents Tagged: 1                                      |
> |                                   Total Share Limits Updated: 1                                    |
> |                                         Run Time: 0:00:00
