### ISSUE TITLE
[FR]: Compatibility with qBittorrent v4.6.0

### ISSUE THREAD

**Issue by Ap0ph1s-W4ite** [StuffAnThings/qbit_manage#429]
### Is your feature request related to a problem? Please elaborate.

After qBittorrent update, qbit-manage starts to log this error:

> `Connecting to Qbittorrent...
> Qbittorrent Error: qbit_manage is only compatible with v4.5.5 or lower. You are currently on v4.6.0. 
> Please downgrade your qBittorrent version to v4.5.5 to use qbit_manage.`

### Describe the solution you'd like

Compatiblity with qBittorrent v4.6.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Seems there are no changes in the qBittorrent API so maybe change the restriction to v4.6.

### Who will this benefit?

Everyone

**Comment by nodiaque** [comment]
You can bypass but if you bypass, sharelimit seems to not work anymore

> 
> ============================= Updating Share Limits based on priority ==============================|
> | Assigning torrents to share limit groups...                                                        |
> |================= Updating Share Limits for [Group maxseeding_14.5d] [Priority 1] ==================|
> |    Torrent Name: Greys.Anatomy.S04.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA                              |
> |         Tracker: https://ssl.empirehost.me                                                         |
> |         Added Tag: sl_1.maxseeding_14.5d                                                           |
> |     Share Limit: Max Seed Time = 21000 min                                                         |
> | Uncaught Exception                                                                                 |
> Traceback (most recent call last):
>   File "/app/qbit_manage.py", line 645, in <module>
>     start_loop()
>   File "/app/qbit_manage.py", line 382, in start_loop
>     start()
>   File "/app/qbit_manage.py", line 491, in start
>     share_limits = ShareLimits(qbit_manager)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/modules/core/share_limits.py", line 36, in __init__
>     self.update_share_limits()
>   File "/app/modules/core/share_limits.py", line 49, in update_share_limits
>     self.update_share_limits_for_group(group_name, group_config, torrents)
>   File "/app/modules/core/share_limits.py", line 224, in update_share_limits_for_group
>     self.tag_and_update_share_limits_for_torrent(torrent, group_config)
>   File "/app/modules/core/share_limits.py", line 257, in tag_and_update_share_limits_for_torrent
>     self.set_tags_and_limits(
>   File "/app/modules/core/share_limits.py", line 382, in set_tags_and_limits
>     torrent.set_share_limits(max_ratio, max_seeding_time)
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 152, in set_share_limits
>     self._client.torrents_set_share_limits(
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 152, in wrapper
>     return func(client, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 117, in wrapper
>     return func(client, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
>     return func(client, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 2008, in torrents_set_share_limits
>     self._post(
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
>     return self._request_manager(
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
>     return self._request(
>            ^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
>     self._handle_error_responses(data, params, response)
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 752, in _handle_error_responses
>     raise MissingRequiredParameters400Error()
> qbittorrentapi.exceptions.MissingRequiredParameters400Error

**Comment by Antorell** [comment]
You need to add a third parameter to the four `torrent.set_share_limits()` in `share_limits.py` until the new feature is added to qbit_manager. 

I used `-1` as I don't use the new share limit, maybe `-2` works to keep whatever is set in the global settings but I can't tell for sure as didn't try.

Something like that
`torrent.set_share_limits(-1, -1, -1)`  (there's three occurences in share_limit.py)
`torrent.set_share_limits(max_ratio, max_seeding_time, -1)`

**Comment by bobokun** [comment]
Please test develop branch and let me know if that fixes the issue. Thanks!

**Comment by nodiaque** [comment]
how do I do that from docker?

**Comment by bobokun** [comment]
> how do I do that from docker?

Use the 'bobokun/qbit_manage:develop' image

**Comment by nodiaque** [comment]
doesn't work

> 
> |================= Updating Share Limits for [Group maxseeding_14.5d] [Priority 1] ==================|
> |    Torrent Name: Greys.Anatomy.S04.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA                              |
> |         Tracker: https://ssl.empirehost.me                                                         |
> |         Added Tag: sl_1.maxseeding_14.5d                                                           |
> |     Share Limit: Max Seed Time = 21000 min                                                         |
> | Uncaught Exception                                                                                 |
> Traceback (most recent call last):
>   File "/app/qbit_manage.py", line 645, in <module>
>     start_loop()
>   File "/app/qbit_manage.py", line 382, in start_loop
>     start()
>   File "/app/qbit_manage.py", line 491, in start
>     share_limits = ShareLimits(qbit_manager)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/modules/core/share_limits.py", line 36, in __init__
>     self.update_share_limits()
>   File "/app/modules/core/share_limits.py", line 49, in update_share_limits
>     self.update_share_limits_for_group(group_name, group_config, torrents)
>   File "/app/modules/core/share_limits.py", line 224, in update_share_limits_for_group
>     self.tag_and_update_share_limits_for_torrent(torrent, group_config)
>   File "/app/modules/core/share_limits.py", line 257, in tag_and_update_share_limits_for_torrent
>     self.set_tags_and_limits(
>   File "/app/modules/core/share_limits.py", line 382, in set_tags_and_limits
>     torrent.set_share_limits(ratio_limit=max_ratio, seeding_time_limit=max_seeding_time)
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1776, in set_share_limits
>     self._client.torrents_set_share_limits(
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1095, in torrents_set_share_limits
>     self._post(
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 514, in _post
>     return self._auth_request(
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 591, in _auth_request
>     return self._request_manager(
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 664, in _request_manager
>     return self._request(
>            ^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 811, in _request
>     self._handle_error_responses(final_data, final_params, response)
>   File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 964, in _handle_error_responses
>     raise MissingRequiredParameters400Error(
> qbittorrentapi.exceptions.MissingRequiredParameters400Error
>

**Comment by bobokun** [comment]
@nodiaque can you please try again?

**Comment by nodiaque** [comment]
working! sorry for the delay.

**Comment by labdiynez** [comment]
@bobokun edit_tracker.py

```
Traceback (most recent call last):
  File "/app/scripts/edit_tracker.py", line 39, in <module>
    torrent.remove_trackers(torrent_hash=(torrent.hash), urls=(x.url))
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 2101, in remove_trackers
    self._client.torrents_remove_trackers(
TypeError: qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_remove_trackers() got multiple values for keyword argument 'torrent_hash'
```

**Comment by Ap0ph1s-W4ite** [comment]
Just to inform that `bobokun/qbit_manage:develop` is working great on my side. Thanks :)

**Comment by bobokun** [comment]
@labdiynez , should be fixed now

**Comment by labdiynez** [comment]
> @labdiynez , should be fixed now

Thanks for the quick fix. Now it works properly.

**Comment by imTHAI** [comment]
I came here to say that switching to `bobokun/qbit_manage:develop` worked for me too. Thank you

**Comment by Ap0ph1s-W4ite** [comment]
As it seems, the solution, for now, it's to switch to develop.
