### ISSUE TITLE
[FR]: share_limits ratio conditionals

### ISSUE THREAD

**Issue by jmxd2** [StuffAnThings/qbit_manage#444]
### Is your feature request related to a problem? Please elaborate.

I would like an option to define different share limits based on current ratio. For example, a reduced max_seeding_time when ratio is above 1.0 and a longer one when it's not to abide by tracker minimum seeding time rules

### Describe the solution you'd like

Something like

min_ratio: 1.0
min_ratio_max_seeding_time: 1440
max_seeding_time: 2940

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I currently do not see any way to check for ratio in the configuration options

### Who will this benefit?

People who are racing while strapped for disk space

**Comment by bakerboy448** [comment]
This doesn't make sense.  Ratio or seed time is whichever is hit first for removal.  If you want to ensure a min seed time is still hit regardless of if the ratio has been met already that attribute already exists
