### ISSUE TITLE
[FR]: Compatibility with v4.6.2 qBittorrent

### ISSUE THREAD

**Issue by imTHAI** [StuffAnThings/qbit_manage#452]
### Is your feature request related to a problem? Please elaborate.

> Qbittorrent Error: qbit_manage is only compatible with v4.6.0 or lower. You are currently on v4.6.1.
> Please downgrade your qBittorrent version to v4.6.0 to use qbit_manag

I already use the develop image since the recommandation for the v4.6.0.

### Describe the solution you'd like

Compatiblity with qBittorrent v4.6.1

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

It's a minor version change, so there may not be much to change about qbit_manage ? 

### Who will this benefit?

Everybody

**Comment by Antorell** [comment]
It's an issue with the required qbittorrent-api package that doesn't know v4.6.1. Until qbt_manage is updated to update to the latest api package, you can remove the version number and the two equals from the `qbittorrent-api` line in the [requirements.txt](https://github.com/StuffAnThings/qbit_manage/blob/5061883b1f89c4a36b761f288ba2479ba4aa1f30/requirements.txt#L3) and pip install -r requirements.txt again to update the package. It will fix the compatibility issue. 

https://github.com/StuffAnThings/qbit_manage/blob/5061883b1f89c4a36b761f288ba2479ba4aa1f30/requirements.txt#L3

**Comment by imTHAI** [comment]
Thank you for the solution. 
But I'm using qbt_manage through a docker. Well, I could build a new container with the Dockerfile and the modified requirements.txt file. But if it is confirmed that this minor qBt's update works well fit qbit_manage, it would be great if the develop image was adapted.

**Comment by bobokun** [comment]
Develop is already on the latest qbit-api version which should support v4.6.1

**Comment by imTHAI** [comment]
![Capture d’écran 2023-11-25 à 15 18 15](https://github.com/StuffAnThings/qbit_manage/assets/36070606/d7627ce7-9a01-4af2-bd61-027310e689f9)

And I checked before there was any update pending.

**Comment by bobokun** [comment]
can you update and try again?

**Comment by imTHAI** [comment]
It works like a charm now ! Thank you @bobokun , you rock.

**Comment by coolguymatt** [comment]
Could you do 4.6.2 as well?

**Comment by imTHAI** [comment]
Indeed 🙁

```
| Connecting to Qbittorrent...                                                                       |
| Qbittorrent Error: qbit_manage is only compatible with v4.6.1 or lower. You are currently on v4.6.2. |
| Please downgrade your qBittorrent version to v4.6.1 to use qbit_manage. 
```

Isn't is possible to let v4.6.x at least for the develop branch ?

**Comment by imTHAI** [comment]
I tried.
  -e 'QBT_SKIP_QB_VERSION_CHECK'='True'

But I still get the error.

| Connecting to Qbittorrent...                                                                       |
| Qbittorrent Error: qbit_manage is only compatible with v4.6.1 or lower. You are currently on v4.6.2. |
| Please downgrade your qBittorrent version to v4.6.1 to use qbit_manage.                            |

It seems that the program does not take into account the variable.

**Comment by Antorell** [comment]
> qbm doesn't control this, the qbittorrent-api does and given qbit's frequent undocumented breaking changes and failure to bump api versions doesn't make this reliable.


Doesn't control it? What's the code checking for version compatibility that checks against  `Version.latest_supported_api_version()` for then? There's also `latest_supported_api_version()` to check against API version. 

https://qbittorrent-api.readthedocs.io/en/latest/apidoc/version.html#qbittorrentapi._version_support.Version.latest_supported_api_version

```
 SUPPORTED_VERSION = Version.latest_supported_api_version()
    MIN_SUPPORTED_VERSION = "2.6"
[...]
            self.current_version = self.client.app.web_api_version
```

will check against API version instead of app version. 


```
| Qbittorrent Error: qbit_manage is only compatible with 2.9.2 or lower. You are currently on 2.9.3. |
| Please downgrade your qBittorrent version to 2.9.2 to use qbit_manage.                             |

```

**Comment by bakerboy448** [comment]
Again, QbitManage has NOTHING to do with qbittorrent-api and what it says is or is not supported.
Again, Qbit does not properly bump their webapi version so you cannot rely on qbit version

**Comment by imTHAI** [comment]
@bakerboy448  Gello, 
Can you explain me how I should enter the ENV  -e 'QBT_SKIP_QB_VERSION_CHECK'='True' as a boolean ? Or is it this variable that is not considered ?

**Comment by bakerboy448** [comment]
Again, 4.6.2 is now supported in develop

**Comment by bakerboy448** [comment]
`QBT_SKIP_QB_VERSION_CHECK=True' as per the docs.
