### ISSUE TITLE
[FR]: Set Tag based on torrent name

### ISSUE THREAD

**Issue by Frazzer951** [StuffAnThings/qbit_manage#470]
### Is your feature request related to a problem? Please elaborate.

I have a bunch of torrents from a torrenting group that I want to give their own category and share limits. They don't have their own tracker, so I can't tag it based on that.
If I was able to give a torrent a tag based on the name. I could then use the cat_change settings to move them to their own category, and then once they are in the category I can change the share limits. 

### Describe the solution you'd like

It would be similar to the tracker section. Were you would give different strings that will be matched against a torrents name, and we can set a tag that that torrent will be given. 

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

N/A

### Who will this benefit?

I think it would benefit most people using this because it allows for even more management and configuration of how we want to use qBit

**Comment by bakerboy448** [comment]
I don't see how this is required. A tag has nothing to do with cat change or share limits.....how is this not possible current stateV

**Comment by Frazzer951** [comment]
The easiest way ive seen to change categories is based on tags.
If you could show me how I could set a category and/or share limits based just on a torrent's name I would appreciate it, but I have not seen how I could do it with the current system. 

But to explain the whole thought process.
I would look for torrents that contain "ReleaseGroup" in their name and give it a tag like "release_group".
Then I would setup a category change to move items from completed with  the tag "release_group" into the 
share_limits category that i'll have my prefered share limits on.

If this is already possible or if you think i'm going at this the wrong way please explain. 

Looking at the config again, I see that the category change isn't even necessary. But still I would need a way to tag torrents based on the name

**Comment by bakerboy448** [comment]
That's not how cat change functions...it simply changes category A to category B

**Comment by Frazzer951** [comment]
For how much you are against this simple feature you have still yet to propose an alternative. Just because you don't see use in a feature doesn't mean its useless to everyone. So unless you have a legitimate reason this would be a bad feature please stop replying

**Comment by bakerboy448** [comment]
Again, the premise of the request: using tags to change categories - is invalid and doesn't exist.

**Comment by Frazzer951** [comment]
The premise of the request is tagging torrents based on their name.
