### ISSUE TITLE
[Docs]: Docker Installation has incorrect QBT_SCHEDULE default value

### ISSUE THREAD

**Issue by NLZ** [StuffAnThings/qbit_manage#475]
### What is the improvement or update you wish to see?

https://github.com/StuffAnThings/qbit_manage/wiki/Docker-Installation says the default value of `QBT_SCHEDULE` is `30`, while https://github.com/StuffAnThings/qbit_manage/wiki/Commands says it's `1440` and that is the correct one.

Also at Commands `--skip-qb-version-check` is missing it's config pair `skip_qb_version_check`, but I don't think it warrants another issue opening.

### Is there any context that might help us understand?

https://github.com/StuffAnThings/qbit_manage/blob/937e9e886f2294eb12e158a058f749d980505c4b/qbit_manage.py#L41-L47

### Does the docs page already exist? Please link to it.

https://github.com/StuffAnThings/qbit_manage/wiki/Docker-Installation

**Comment by bakerboy448** [comment]
PRs welcome https://github.com/StuffAnThings/qbit_manage-wiki
