### ISSUE TITLE
[FR]: Force setting a category for a tracker

### ISSUE THREAD

**Issue by mat926** [StuffAnThings/qbit_manage#483]
### Is your feature request related to a problem? Please elaborate.

If a torrent has a category already set , qbit_manage will not update the category to the one I already specified in the config. 

### Describe the solution you'd like

Add a flag for each tracker that forces qbit_manage to update the category for that tracker if a category is already set. For example

```
tracker:
  myanonamouse:
    tag: MaM
    cat: other
    force_update: true
```

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I tried setting a default category in Prowlarr and mapping the categories from there but it still doesn't give me an option to map it by tracker. 

### Who will this benefit?

N/A

**Comment by bobokun** [comment]
No new config option, this will just update automatically if the category is defined in the tracker section. Please test in the latest develop branch. Thanks

**Comment by Ap0ph1s-W4ite** [comment]
I'm not sure if I have something wrong with my configuration, but now qbit-manage is forcing all torrents that I have set manually. there is any option to avoid this?

I have a category and if I create a torrent for a file inside a directory, it will create a new category with the same name as that directory.

**Comment by TheGFactor** [comment]
Definitely hope this is considered. My fault for not fully understanding and considering all breaking changes before updating, but I've experienced massive data loss at the hands of already-set categories just getting completely wiped.

**Comment by bakerboy448** [comment]
? This is already in 4.1.5

**Comment by TheGFactor** [comment]
> ? This is already in 4.1.5

My apologies, I submitted my comment on the wrong tab. I meant to post this to the issue currently open asking for a way to disable the behavior implemented here. Since updating to 4.1.5, catagoties I had manually set were overwritten and then immediately purged, causing 3-4TB of data loss.
