### ISSUE TITLE
[FR]: "STREAM TRUNCATED" status message on TL

### ISSUE THREAD

**Issue by mat926** [StuffAnThings/qbit_manage#497]
### Is your feature request related to a problem? Please elaborate.

Some trackers like TL often gets tagged as an issue for `stream truncated` and then get untagged on the next run. This can happen consecutively which is annoying. 

### Describe the solution you'd like

An ideal solution would be to tag them only if they failed 3 consecutive number of times before sending a webhook notification. And untag them if they are working.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

None

### Who will this benefit?

TL users.

**Comment by SnippetSpace** [comment]
Seeing the same issue here. Important note is that in all my cases TL comes with 2 tracker urls:
https://tracker.tleechreload.org/a/passkey/announce
https://tracker.torrentleech.org/a/passkey/announce

in my case the "stream truncated" message appear son the tleechreload.org tracker, but the torrentleech.org tracker shows up as working.

I guess if 1 of the 2 works it should not be tagged as an issue.

**Comment by bobokun** [comment]
@SnippetSpace , thanks for the investigation. As part of #595, I've also implemented a fix for this so if one of the two trackers are working then it won't be considered an issue. Please let me know if you're still seeing this issue on the latest develop branch.
