### ISSUE TITLE
[FR]: Automatically add tag to "partial" downloaded torrents

### ISSUE THREAD

**Issue by m6man** [StuffAnThings/qbit_manage#498]
### Is your feature request related to a problem? Please elaborate.

Issues with cross-seeds and broken files can be annoying to analyze and fix when caused by (related) torrents where not all files are selected for download.

Unwanted files often get created anyway because the pieces for the wanted files often overlap with unwanted files.

And when pre-allocation is enabled, those unwanted files (e.g. other TV show episodes) are just as big as the other files, making it also harder to detect why they are not working. You'd need to check all torrents that might include this file and then see if it might be unwanted.

### Describe the solution you'd like

I think it would be useful if qbit_manage could automatically add a custom tag to all torrents where at least one file is set to "Do not download" / "Unwanted". As the default i suggest "partial".

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

It might be possible to change the GUI of VueTorrent to have this as a column, but it might be significantly more work than scanning with qbit_manage and adding a tag.

The other alternative would be a custom script that does something similar to what qbit_manage does, but that scans specifically for partial torrents.

### Who will this benefit?

Anyone that has partial torrents in combination with cross-seeding, hardlinking, *arr setup etc.

Anyone that downloads only the sample video file or the first video file of a TV show pack to check it out and has cross-seed running.

**Comment by bakerboy448** [comment]
This is a highly niche use case and have never heard of anyone partially downloading torrents and cross-seeding them. It makes no sense for anyone to do that.

QBm also does not operate on non-complete (I.e. not downloaded or seeding or stopped torrents)

> Unwanted files often get created anyway because the pieces for the wanted files often overlap with unwanted files.

that's a qbit bug you need to report to qbit if it is still downloading files you didn't tell it to
