### ISSUE TITLE
[FR]: Support for other cross-seeding apps (i.e Crops and Pollenizer) (--cross-seed) folder inject

### ISSUE THREAD

**Issue by mat926** [StuffAnThings/qbit_manage#503]
### Is your feature request related to a problem? Please elaborate.

I use other cross-seed apps like [Crops](https://github.com/soranosita/crops) and Pollenizer which are designed for specific private trackers since they don't make as many requests like [cross-seed](https://github.com/cross-seed/cross-seed) does. I have [cross-seed](https://github.com/cross-seed/cross-seed) set up to inject directly into qBittorrent for other private trackers. The cross-seed folder that qBit_manage uses may be useful for other cross-seeding apps that don't support direct injection. Currently I use it as a watch folder in qBittorrent since qBit_manage does not support torrent files generated by these apps. 

### Describe the solution you'd like

Please add cross-seed support for Crops and Pollenizer, etc. 

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

NA

### Who will this benefit?

Crops, Pollenizer and other cross-seeding apps users. 

### Additional Information

File name examples generated by Crops:
```
1966 - Gabor Szabo - Jazz Raga [2010 WEB FLAC][Verve Reissues][602527584546] [RED].torrent
A_Teens - Teen Spirit (2001) [FLAC] {013 401-2} [RED].torrent
Avicii - Tim (2019) [FLAC] {B0030536-02} [RED].torrent
Basshunter - Now You're Gone - The Album (2008) [WEB FLAC] [RED].torrent
Bastille - Bad Blood X (2013 - 2023 Reissue) {5565281} [CD FLAC] [RED].torrent
Rush - 2112 (1976) {B0017747-00, BD, 2.0} [FLAC 96-24] [OPS].torrent
UB40 – The Very Best Of UB40 1980 - 2000 (2000) [7243 8 50469 2 6] {CD-FLAC} [OPS].torrent
Loraine - An Autumn Evening (2023) - WEB MP3 320 [OPS].torrent
```

File name examples generated by Pollenizer:
```
ops.2575826.torrent
red.1043479.torrent
red.4729433.torrent
```

**Comment by bakerboy448** [comment]
Please explain and provide trace logs how the existing `--cross-seed` function does not work.

https://github.com/StuffAnThings/qbit_manage/blob/46518577f956fcbf2b18d36c4e9c6d3908b01a95/modules/core/cross_seed.py#L24

"add torrents from the cross-seed output folder to Qbittorrent"

**Comment by mat926** [comment]
I just get parse errors because the file names are in a different format
```
|================================= Checking for Cross-Seed Torrents =================================|
| Uncaught Exception                                                                                 |
Traceback (most recent call last):
  File "/app/qbit_manage.py", line 643, in <module>
    start_loop()
  File "/app/qbit_manage.py", line 382, in start_loop
    start()
  File "/app/qbit_manage.py", line 460, in start
    cross_seed = CrossSeed(qbit_manager)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/modules/core/cross_seed.py", line 21, in __init__
    self.cross_seed()
  File "/app/modules/core/cross_seed.py", line 37, in cross_seed
    tr_name = file.split("]", 2)[2].split(".torrent")[0]
              ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by ShanaryS** [comment]
In v6, cross-seed will watch a directory for .torrent files and try to match and inject.

It hasn't been tested for your use case but it should work.
