### ISSUE TITLE
[FR]: I want to retag all torrents.  

### ISSUE THREAD

**Issue by Zenya393** [StuffAnThings/qbit_manage#513]
### Is your feature request related to a problem? Please elaborate.

qbit_manage won't tag torrents that already have torrents, unless you specify tags to ignore.
If I tag a torrent before qbit_manage, then qbit_manage won't tag, unless I have the tag in the ignore list.

I have some torrents with a bunch of tags, and I need to retag those torrents (e.g. tracker=other).

### Describe the solution you'd like

I want to force qbit_manage to retag all torrents.

Potential solutions:
1. Force retagging.
2. ignoreTags_OnUpdate = False.
3. Allow a wildcard to ignoreTags_OnUpdate.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Manually copy tags from QBT and put into config.yml.
Every time a new tag is created, have to update config.yml.

### Who will this benefit?

All that extensively use tagging.

**Comment by bakerboy448** [comment]
config book option of `force_retag` # Ignores All Tags and will always retag every torrent *may cause performance issues*

And adding it as an or https://github.com/StuffAnThings/qbit_manage/blob/29690e9581689c0e86b4cdf8aa9a5a4915996b28/modules/core/tags.py#L28

would likely be the least painful route

**Comment by bakerboy448** [comment]
Added to develop 

force_retag_all: false # Forces all torrents to be updated on every run (may cause performance issues). This does not remove any previous tags assigned
