### ISSUE TITLE
[BUG] - name 'client' is not defined

### ISSUE THREAD

**Issue by afraazali** [StuffAnThings/qbit_manage#52]
On line 344 `client.torrents.add(torrent_files=src, save_path=dest, category=category, tags='cross-seed', is_paused=True)` in `/modules/qbittorrent.py`. I believe this should be `self.client`?

Also it looks like `shutil` isn't imported in `/modules/qbittorrent.py` so there's an error thrown on line 345

**Comment by bobokun** [comment]
Yup! Thanks for catching that. It's fixed in the latest develop branch

**Comment by afraazali** [comment]
Thank you @bobokun. How long does it take to deploy a new docker image?

**Comment by bobokun** [comment]
Not long, it is all automated, <5minutes. It's updated now

**Comment by afraazali** [comment]
Amazing. Thank you!
