### ISSUE TITLE
[Bug]: set_tags_and_limits no longer works when the torrent doesn't have associated tags

### ISSUE THREAD

**Issue by ColinHebert** [StuffAnThings/qbit_manage#522]
### Describe the Bug

The application crashes when trying to apply share limits when the group doesn't add a tag.

This is likely due to the logic change in https://github.com/StuffAnThings/qbit_manage/pull/520/files#diff-c21a82cd9e26e49111b0dd364f4793029a1586dfe7fc114449f4e84692a1e279L362-L363

### Logs

https://gist.github.com/ColinHebert/fba1ad85003b73076cbf8098993b3d68

### Installation

Docker

### Version Number

4.1.0

### What branch are you on?

master

**Comment by bobokun** [comment]
Can you please also share the share_limits section of your config?

**Comment by bobokun** [comment]
Can you please update to the latest develop branch and let me know if this fixes the issue?

**Comment by NLZ** [comment]
Had the same issue, the bobokun/qbit_manage:develop container works
