### ISSUE TITLE
[FR]: Tag moving files and tag moving files with error

### ISSUE THREAD

**Issue by Zenya393** [StuffAnThings/qbit_manage#531]
### Is your feature request related to a problem? Please elaborate.

I cannot easily tell which torrents are moving, or how many.
I cannot easily tell which torrents that are moving have an error associated with the move.

### Describe the solution you'd like

I would like torrents with the status "Moving" to be tagged "Moving" so I can easily/quickly identify which torrents are in the middle of a move, and how many.

This can also be useful if you don't see torrent moves being completed that it indicates a problem.  The qBittorrent WebUI won't let you know there's a problem, so you have to look for it.

Might also be nice to have two types of tags:
Moving (normal moving)
Moving-Error (moving encountered error)

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Ideally the qBittorrent WebUI would have a status category for "Moving".

### Who will this benefit?

When one or more torrents are being moved, this will be easy to see which ones, how many.  If you don't see the moves completing, it indicates there's a possible problem, and to go look at the logs.

**Comment by bakerboy448** [comment]
What is your use case and setup that you have 1) qbit moving multiple torrents constantly, where 2) the moves are extremely slow that a QBm run every several hours would have a material use

**Comment by Zenya393** [comment]
I'm just looking for two tags:

Moving
Tag torrents "Moving" when status = Moving.  This includes queued moves, active moves, error moves.

Moving-Error
Tag torrents "Moving-Error" when there's a moving error in the execution log.

I have had 15 moves at the same.
I have had moves error out (usually storage space issue).
I have had moves stuck.
Maybe some moves are queued because other torrents are being checked.

**Comment by bakerboy448** [comment]
Please provide answers to the questions.

**Comment by Zenya393** [comment]
How would I know the moves have issue when I didn't even know there were moves?
Having them tagged helps me know there is an issue, or if there's a move queue.

**Comment by bakerboy448** [comment]
Closing no plans
- out of qbm scope
- OP repeatedly failed to provide additional details for the use
- Invalid feature request, no usecase
