### ISSUE TITLE
[FR]: UID/GID Mapping Support

### ISSUE THREAD

**Issue by undaunt** [StuffAnThings/qbit_manage#532]
### Is your feature request related to a problem? Please elaborate.

When folders are created within the recycled or orphaned torrent structure, they are owned by root:root. This in and of itself is not a problem, but it would be ideal to have the ownership match the qBittorrent container and host OS user, if possible.

### Describe the solution you'd like

Please support mapping of UID/GID, particularly for the mkdir function or any file/folder actions if possible.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I regularly run the following within my downloads folder to update, and understand what has been updated, with respect to ownership, but it is not the ideal fix:

`sudo chown -Rv undaunt:undaunt * | grep changed`

### Who will this benefit?

Users who may want to move folders or files back out of recycled and orphaned, or keep permissions aligned within their downloads folder structures.

### Additional Information

Thanks for your consideration.

**Comment by bakerboy448** [comment]
PUID and PGID support is not required to change the user the container runs as - docker run and docker compose already natively support functionality to do so.

**Comment by undaunt** [comment]
@bakerboy448 Thanks for clarifying, I was able to use `user: UID/GID` successfully, just wasn't sure if that would work as sometimes it causes permission issues with some images based on how they are written. Working well now after I chown'd the existing log files.
