### ISSUE TITLE
[FR]: Process a single torrent

### ISSUE THREAD

**Issue by AN1MATEK** [StuffAnThings/qbit_manage#535]
### Is your feature request related to a problem? Please elaborate.

When a torrent is added to the client, optimally it should be processed by QBM right away. Some `share_limits` may be too short if QBM is to be run once a day. Running it too often can unnecessarily spin-ups the HDDs.

### Describe the solution you'd like

Having a webhook similar to how cross-seed works, where the `info_hash` would be posted from the torrent_added script from the client. QBM should process that torrent alone,  tag it, set the `share_limits`, etc. not caring about the rest.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

I tryed running QBM on each new torrent, but that created another set of problems, specially when cross-seeding occurs, as many torrents are added at once. 
I also have some scripting going on on new torrents to add the tracker's tag, which works fine, but I am missing on the `share_limits`. That could be relatively easy to implement at this stage, but the maintenance would be a mess.

### Who will this benefit?

Me. People using seed-boxes. Serious torrenters. If this gets implemented, QBM can be mindlessly run once a day, saving a lot of CPU cycles for a ton of users.

### Additional Information

Just a huge thank you to bobokun for this awesome tool

**Comment by bakerboy448** [comment]
You can already use a qbit on complete script to run qbm with -r with whatever commands as applicable

**Comment by AN1MATEK** [comment]
> You can already use a qbit on complete script to run qbm with -r with whatever commands as applicable

If it runs on complete, it will not cover cross-seeded torrents. If it runs on added, sometimes many get added at once, which also does not work. On top of that it runs through +1k or more torrents unnecessarily.

The only solution at the moment is to run QBM more often, what is also inefficient. 

A simple webhook to post a hash would make a great solution. 

I want to point out that I am not the only one who has encounter this limitation.
