### ISSUE TITLE
[Bug]: Incorrect noHL Tags on Hardlinked Torrents

### ISSUE THREAD

**Issue by TheTrustyHammer** [StuffAnThings/qbit_manage#544]
might be radarr issue....

**Comment by TheTrustyHammer** [comment]
FYI in the past noHL would be for .rar'd files. This file "The Chase" is a simple .mkv file. Makes no sense why it is claiming this file to be a noHL.

**Comment by bakerboy448** [comment]
A movie existing in radarr as per your screenshot in no way shape or form implies or indicates in anyway that anything was hardlinked.

this will also be unlikely to be a radarr issue/bug and is basically guaranteed to mean you have a setup that does not facilitate hardlinks
