### ISSUE TITLE
[FR]: Option to completely customize tag name.

### ISSUE THREAD

**Issue by devanteweary** [StuffAnThings/qbit_manage#551]
### Is your feature request related to a problem? Please elaborate.

Currently tag names are named as a combination of SHARE_LIMITS_TAG + SHARE LIMIT PRIORITY + SHARE LIMIT NAME with a few underscores added in.

### Describe the solution you'd like

I'd love to be able to customize the name so that it's more... aesthetic? 
And a little easier to determine at a glance.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Perhaps it can be done within the share limit itself?  
For example, if we call the new option **tag_name**

```
share_limits_tag: seeding

share_limits:
	reading:
		priority: 1
		categories:
		- Books
		- Comics
		- Magazines
		max_seeding_time: -1
		cleanup: false
		tag_name: Reading
```

Then in qBittorrent, the tag would be called simply "Reading".

As of now, without the "new" tag option, the tag in qBittorrent will be called "seeding_1.reading"

Either that or have it name the tag whatever the share_limit name is, if that makes sense.

### Who will this benefit?

I just feel like it would _look_ a lot better for sure, as well as make it quicker at a glance to determine what it is.

In the above example, I'd love to be able to call the tag "Reading" instead of "seeding_1.reading"

### Additional Information

Thank you for taking the time to read this and love the program!!!!

**Comment by bakerboy448** [comment]
How does this not already exist? You can already customize the tag names.

Please read the docs and config prior to opening feature requests for existing functionality

https://github.com/StuffAnThings/qbit_manage/blob/f4dcc3900c7053c1376d458f13b1fc742a74309e/config/config.yml.sample#L31

**Comment by devanteweary** [comment]
> How does this not already exist? You can already customize the tag names.
> 
> Please read the docs and config prior to opening feature requests for existing functionality
> 
> https://github.com/StuffAnThings/qbit_manage/blob/f4dcc3900c7053c1376d458f13b1fc742a74309e/config/config.yml.sample#L31

Sorry if I didn't explain it correctly.

Yes just like above, you can customize the tags to a point.  
But according to my tests and the documentation, no matter what, the tags will be a combination of **share_limit_tag** + **priority** + **share name**.

So it will always be something like: sharetag_1.sharename

What I'm requesting is to be able to clean the name up by adding something like: tag_name

Where, if used, tag_name will be used in qBittorrent instead of the combination qbit_manage uses currently.

So in the example above, instead of the qBittorrent tag being named 
**seeding_1.reading**, you could use tag_name to have it show up as something as simple as  "Books" in qBittorrent.

Hope that makes sense!

**Comment by bobokun** [comment]
Hi @devanteweary , thanks for opening the FR. I understand your request, however currently the `share_limits_tag` is a requirement for qbm to understand which tags are related to share limits. There can be other applications or a user adding manual tags which qbm is not aware of. Share limits can change and a torrent that was assigned a share limit tag can later change to a different priority if for example it gets tagged as `noHL` or if you change your qbm config. Once a torrent gets assigned a new share limit priority , the old tag gets removed and replaced with the new share limit tag. With your approach of customizing the tag_name, if you were to change the qbm config to a different tag name or if the torrent changes to a different share priority, qbm would not know which tag to remove as it becomes ambiguous.

Hope I'm able to explain this okay, but my suggestion is to change your `share_limits_tag` to something with fewer characters such as `sl`, then it would be easier to read. If the priority is not important maybe we can exclude the priority from the tag such that it's `share_limit_tag + share name` instead.

**Comment by devanteweary** [comment]
> Hi @devanteweary , thanks for opening the FR. I understand your request, however currently the `share_limits_tag` is a requirement for qbm to understand which tags are related to share limits. There can be other applications or a user adding manual tags which qbm is not aware of. Share limits can change and a torrent that was assigned a share limit tag can later change to a different priority if it gets tagged as `noHL` or if you change your qbm config. Once a torrent gets assigned a new share limit priority , the old tag gets removed and replaced with the new share limit tag. With your approach of customizing the tag_name, if you were to change the qbm config to a different tag name or if the torrent changes to a different share priority, qbm would not know which tag to remove as it becomes ambiguous.
> 
> Hope I'm able to explain this okay, but my suggestion is to change your `share_limits_tag` to something with fewer characters such as `~sl`, then it would be easier to read. The reason why I included the priority in the tag name as well is so that it gets sorted in qbt by priority when displaying the tags. If the priority is not important for you maybe we can add an option to exclude the priority from the tag such that it's `share_limit_tag + share name` instead.

THank you for the reply. :>

Sure even removing the priority would be awesome.  
With that in mind, at least in my case, I could get it down to Books.. (using the above example).
(the second period being the name of the share limit, I call mine just a period to try to hide it a little).

Oh and thanks for taking the time to write out that explanation!
And for the program in general.

**Comment by devanteweary** [comment]
Test reply from email.
________________________________

**Comment by bobokun** [comment]
>(the second period being the name of the share limit, I call mine just a period to try to hide it a little).

I would caution using a share_limits_tag that is something like a period `.` because as per my previous explanation, qbm will look for any previous share_limits_tag and remove them from the tags before applying the new tag. If you set it to `.` then ANY tag in your torrent containing a `.` will be removed since qbm will think that tag was a previous share_limit. This could lead to some unexpected tag removals

**Comment by bobokun** [comment]
Well lucky you :) I thought of a way to implement this allowing you to customize tags. Please switch over to the develop branch to test. Let me know if you find any bugs. Thanks! The new key to add in your config is found here: https://github.com/StuffAnThings/qbit_manage/blob/ba40c5cefbe8d5044e7a2cf8f0a412a48b255d48/config/config.yml.sample#L219-L220
