### ISSUE TITLE
Potentiall unregistered torrent

### ISSUE THREAD

**Issue by Davo1624** [StuffAnThings/qbit_manage#56]
If a torrent has two trackers (for example tleechreload and torrentleech) and the torrent is removed from one of the trackers but is still active on the other tracker qbit_manage will report the torrent as potentially unregistered.

**Comment by bobokun** [comment]
Anything that gets marked as potentially unregistered will not have any action taken on it. It's just to identify any errors in torrents that are not on the unregistered torrents list. Do you have logs to share of the example above?

**Comment by Drazzilb08** [comment]
```Torrent Name: AWesome movie.1988.1080p.BluRay.x264.DTS-HD.MA-Group.mkv
Status: NOT FOUND
Tracker: https://tracker.tleechreload.org```

This is what he is referring to. 🙃

One we didn't account for.

**Comment by bobokun** [comment]
`NOT FOUND` is too generic and caused a lot of positives, especially since you experienced that first hand @Drazzilb08 and that was the reason I implemented recycle bin in the first place 🤪

**Comment by Drazzilb08** [comment]
Agreed. It might be something that just has to sit there letting you know.
