### ISSUE TITLE
[FR]: Remove orphaned without moving to orphaned_dir

### ISSUE THREAD

**Issue by ScaredyCatX** [StuffAnThings/qbit_manage#590]
### Is your feature request related to a problem? Please elaborate.

As of now, when removing orphaned torrents, qbm first moves the files to `orphaned_dir` then delete them based on `empty_after_x_days`. The moving process isn't necessary when the value is 0, which cause high IO when moving files between drives just to delete them afterwards

### Describe the solution you'd like

My suggestion is to add an if statement to check if the value of `empty_after_x_days=0`, if it is, then skip the whole moving process and just delete the files.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

I created 3 qbm config files:

1. Deals with tagging, share limits, and clearing torrents (basically, everything other than removing orphaned)
2. Only remove orphaned option is enabled with the `orphaned_dir` located on the SSD
3. same as 2 but with the `orphaned_dir` located on the HDD

### Who will this benefit?

Anyone with multiple drives who's not using unRAID, especially for racing.

**Comment by bobokun** [comment]
This has been added to develop. Please test and let me know if you run into any issues. Thanks!

**Comment by ScaredyCatX** [comment]
I have just tested it, all good, It deletes orphaned immediately as expected.
