### ISSUE TITLE
[Bug]: QBM keeps calling BHD API when rate limited

### ISSUE THREAD

**Issue by NLZ** [StuffAnThings/qbit_manage#593]
### Describe the Bug

When BHD says you are rate limited qbit_manage continues trying with other torrents, which is I think is unwise, would be better to stop checking BHD for that run.

The API response in this case is `{"status_code":0,"status_message":"Invalid API action: You have been rate limited.","success":false}` with status code 200.

### Logs

https://logs.notifiarr.com/?4adf0c53b5af5e8d#DfjLMMHASG3gA197cJuF4V1oBqEG4vY8CaoMU9GMV4s5

### Installation

Docker

### Version Number

4.1.6

### What branch are you on?

master

**Comment by bakerboy448** [comment]
confirmed

**Comment by bobokun** [comment]
Fixed in #595
