### ISSUE TITLE
[BUG] - Category XYZ is defined under nohardlinks attribute but is not defined in the cat attribute. 

### ISSUE THREAD

**Issue by afraazali** [StuffAnThings/qbit_manage#61]
I've seen the following error in my logs:

```
modules.util.Failed: Config Error: Category Permaseed is defined under nohardlinks attribute but is not defined in the cat attribute. 

Config Error: Category Permaseed is defined under nohardlinks attribute but is not defined in the cat attribute.
```

I manually categorize torrents as **Permaseed** if I choose to keep them. IE 4K movies and TV episodes. Sometimes the *arrs will upgrade a movie/episode and I'll want to remove whatever was permaseeded in favour of the upgrade. So my workflow goes:

1) Find the old permaseed-ed torrent (NoHL option does this for me now)
2) Delete the old permaseed-ed torrent along with the files
3) Find the upgraded torrent
4) Categorize it as **Permaseed**
5) Set no share limit

I have a another "permaseed" category for cross seeding purposes, **cross-seed-permaseed**. This basically tags any cross seeds found for permaseeded torrents and categorizes it as **cross-seed-permaseed**.

I went in and added the **Permaseed** category to the `cat` property in the config, but that was marking my cross-seeded torrents as **Permaseed** and not cross-seed-permaseed.

Any solution to this? Perhaps I can set up my config differently?

**Comment by bobokun** [comment]
is your `Permaseed` and `cross-seed-permaseed` categories sharing the same save directory?

**Comment by afraazali** [comment]
Yes. They share the same save dir.

**Comment by bobokun** [comment]
you'll have to change it so it's not in the same directory, so maybe put the cross-seed ones in `/permaseed_directory/cross-seed/` ?

**Comment by afraazali** [comment]
That would defeat the purpose of cross seed, no? I’d be downloading two of the same files.

**Comment by bobokun** [comment]
>I have a another "permaseed" category for cross seeding purposes, cross-seed-permaseed. This basically tags any cross seeds found for permaseeded torrents and categorizes it as cross-seed-permaseed.

I'm not quite understand what the purpose of changing the category to `cross-seed-permaseed` when the save path is the same. Why not just use `cross-seed` tag and leave the category as `permaseed` since it's in the same save_path location. I'm not really sure what you're trying to accomplish

**Comment by afraazali** [comment]
I'll give that a try. I had it setup like this for organization purposes and also so the *arrs aren't constantly trying to import files. Along with a `cross-seed-permaseed` category, I have one for `cross-seed-tv` and `cross-seed-movies`. I _could_ also just have `nohardlinks` monitor the `cross-seed-permaseed` category and that _should_ allow me to see if any torrents don't have hardlinks.

**Comment by bobokun** [comment]
> *arrs aren't constantly trying to import files.
to solve this I have a Sonarr category and a SonarrComplete category, similar with Radarr. So the *arrs only look at the Sonnarr/Radarr category (which most of the time is empty) and after it imports successfully then it will change the category to the Complete one.

**Comment by afraazali** [comment]
Makes sense. I'll close this out. Thank you again.
