### ISSUE TITLE
[FR]: tracker: only add tag if matched to a rule I.e. don't create new tags

### ISSUE THREAD

**Issue by JWWolstenholme** [StuffAnThings/qbit_manage#652]
### Is your feature request related to a problem? Please elaborate.

The tracker tagging feature ensures that every torrent has at least one tracker-related tag on it. It creates new tags when it can't find an existing one based on the tracker rules set in the config (unless `other` is used).

### Describe the solution you'd like

The way I'd like to use tags for trackers is to have qbit_manage add tags where possible based on rules, but then ignore torrents where it can't find a rule. That way I can go through on a case-by-case basis and manage those myself, or create new rules for them if appriopriate.

More specifically, another config option to disable creation of new tags when no match is found and `other` is not set would fit my desired use-case.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I've considered just leaving the `other` rule set, but that means every torrent that doesn't match my rules will have that tag in addition to whatever tag I set manually, making it redundant.

### Who will this benefit?

Users of the 'tracker' function, especially those who utilise many different trackers that they don't want to create rules for, but still want to track via tags (manually).

**Comment by bakerboy448** [comment]
so summarizing the request:

Allow setting `tag` for trackers not covered and would fall under other `as blank` ?

**Comment by JWWolstenholme** [comment]
> so summarizing the request:
> 
> Allow setting `tag` for trackers not covered and would fall under other `as blank` ? 

Yes sir.

**Comment by bakerboy448** [comment]
Should be able to do this existing - set the tag to `""`

**Comment by JWWolstenholme** [comment]
> Should be able to do this existing - set the tag to `""`

Oh, awesome. I can confirm that works as I hoped it would. Thanks!

Maybe it's worth including a line in the sample config file mentioning this?
