### ISSUE TITLE
[FR]: Log retention

### ISSUE THREAD

**Issue by daviddanko** [StuffAnThings/qbit_manage#656]
### Is your feature request related to a problem? Please elaborate.

I would like to request a feature that allows for configuration of log retention policies. Currently, qbit_manage generates logs for indefinitely and we don’t have native mechanisms for purging logs after a certain period.

### Describe the solution you'd like

Introduce an environment variable or config file option that can define:

- Maximum log file size (in MB).
- Maximum number of log files to retain.
- Maximum log retention period (e.g., 7 days).

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

N/A

### Who will this benefit?

Everyone

**Comment by bobokun** [comment]
It's actually not indefinite, right now it's hardcoded to 10MB per file with a maximum of 5 files.

**Comment by bobokun** [comment]
You can use `QBT_LOG_SIZE` and `QBT_LOG_COUNT` now to determine the size (in MB) or the number of logs to keep via environment variables. CLI can be used as well `--log-size`  / `--log-count` . This won't cleanup any existing logs so you would need to delete those yourself first. You can test this in the develop branch
