### ISSUE TITLE
[FR]: Support qB v4.6.7

### ISSUE THREAD

**Issue by Piddox** [StuffAnThings/qbit_manage#657]
### Is your feature request related to a problem? Please elaborate.

Hi bobokun,
Could you add support for qB v4.6.7?
Highly appreciate your continued work!
Thanks

### Describe the solution you'd like

Support qB v4.6.7

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Downgrading qB to v4.6.6 but I don't want to do that =)

### Who will this benefit?

Everyone!

**Comment by bakerboy448** [comment]
Feature requests for new qbit support are unecessary.  Dependabot bumps qb-api once a new version exists

https://github.com/StuffAnThings/qbit_manage#supported-qbittorrent-versions
