### ISSUE TITLE
[Bug]: Uncaught exception in orphaned deletion causing crash

### ISSUE THREAD

**Issue by xTnK** [StuffAnThings/qbit_manage#675]
### Describe the Bug

Crash while trying to delete orphaned.

In the log, trackers and torrent names have been redacted on purpose

### Logs

https://gist.github.com/xTnK/73f0ac3e5c24b8875c2cbe27fc0eacf9

### Installation

Docker

### Version Number

4.1.11

### What branch are you on?

master

**Comment by bakerboy448** [comment]
It appears you enabled remove orphaned yet failed to set an orphaned directory.

This does not appear to be a bug

**Comment by bakerboy448** [comment]
You also have numerous configuration errors including  depreciated BHD attribute and misconfigured notifications for apprise.

**Comment by xTnK** [comment]
> It appears you enabled remove orphaned yet failed to set an orphaned directory.
> 
> This does not appear to be a bug

My bad then, but it might be worth to still catch the error
