### ISSUE TITLE
[FR]: allow setting share limits for torrent not yet seeding

### ISSUE THREAD

**Issue by vancrize** [StuffAnThings/qbit_manage#676]
### Is your feature request related to a problem? Please elaborate.

I am satisfied with the solutions qbitmanage delivers, but i expected that my sharelimit group apply to all torrents, not just the seeding ones. I have a tracker based tag system and use this tags to primarily control upload limits even when still downloading. Most of the time a torrent is using bandwidth, which i would want for others available.

Is this a misconfiguration or is that behavior by design?

### Describe the solution you'd like

I would love to differentiate between torrent status for sharelimit groups.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I tried different combinations of group settings to observe their behavior, but none suited my need completely.

### Who will this benefit?

Everyone who wants to have control over their bandwidth over the span of a torrents lifetime, not just when its seeding.

**Comment by bakerboy448** [comment]
This exists...?

Use `share_limits_filter_completed`
