### ISSUE TITLE
[FR]: Option to disable auto-folder creation.

### ISSUE THREAD

**Issue by devanteweary** [StuffAnThings/qbit_manage#681]
### Is your feature request related to a problem? Please elaborate.

Kinda not really but sort of.  
The "problem" is qbit_manage creates categories if you save your torrents to folders not defined in the config.

For instance, in this example, my default save-to folder is `/downloads/Unsorted`
Now if for whatever reason I manually set a download to `/downloads/Unsorted/some_kinda_os` after a little while, qbit_manage will have the following error and then create the categories with the same name as the folder.

`Existing category "some_kinda_os" not found for save path /downloads/Complete/Unsorted/some_kinda_os, category will be created.`

This is an issue because it creates clutter in your categories and I've heard it even messes with cross-seeding although I don't know much about that.

![image](https://github.com/user-attachments/assets/48711679-73ff-4184-b26d-90a87960108b)

### Describe the solution you'd like

Just a simple option in the config like "folder_create = false" or something.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I know we can set folders to categories in the config, but everytime I manually set a download folder it's on the fly to group several torrents together in my folder structure, so manually setting them in the config each time isn't really viable.

### Who will this benefit?

Everyone who doesn't like auto-categories. People like me who want clean and organized setups.

### Additional Information

Thank you for listening!

**Comment by bobokun** [comment]
>The "problem" is qbit_manage creates categories if you save your torrents to folders not defined in the config.

All categories must be defined in the configuration and is a requirement.
https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#cat

**Comment by devanteweary** [comment]
> > The "problem" is qbit_manage creates categories if you save your torrents to folders not defined in the config.
> 
> All categories must be defined in the configuration and is a requirement. [Wiki: Config Setup (cat)](https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#cat)

I realize that. I was just requesting an option to do away with that requirement.    
Like... I can't be the only one who sets impromptu download folders once in a while.
