### ISSUE TITLE
[FR]: Support for qbt v5.0.2

### ISSUE THREAD

**Issue by imTHAI** [StuffAnThings/qbit_manage#696]
### Is your feature request related to a problem? Please elaborate.

Hello,

I know [you said ](https://github.com/StuffAnThings/qbit_manage/issues/657#issuecomment-2368072699) that FR for new qbit support is not necessary.
But the [qbittorrent-api](https://pypi.org/project/qbittorrent-api/) supports the v5.0.2 since the 17th of Nov, and I'm using the develop version.

I didn't quite understand when you said "Dependabot bumps qb-api once a new version exists" 
Does that mean that support in the develop branch is automatic (via a webhook or something) when api is updated, in which case it sounds like something has stuck. Or do you have to do some adaptation or precheck?

Thank you for this great tool !

### Describe the solution you'd like

support of qbt v5.0.2 at least in the develop branch.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

To downgrade my qbt version. 

### Who will this benefit?

I suppose this concerns a lot of people, at least those who use qbt as a docker container, since they're usually configured to fetch new images as soon as they're published.

**Comment by bakerboy448** [comment]
Closing per prior comments

**Comment by bakerboy448** [comment]
https://github.com/StuffAnThings/qbit_manage/commit/fa49f866408444e9c4b64f26e68bb1937ac8ceee

**Comment by lo97** [comment]
@bakerboy448 the PR you linked is blocked because of approvals problems ,can you take a look? thanks

**Comment by bakerboy448** [comment]
What are you talking about? The linked commit is the requirements bump in dev

**Comment by lo97** [comment]
https://github.com/StuffAnThings/qbit_manage/actions/runs/11990134951/job/33427307898

**Comment by bakerboy448** [comment]
CI for updating the supported versions file has no relevance.

If you looked - it always fails.

**Comment by bakerboy448** [comment]
#792 will bump develop with the new module
