### ISSUE TITLE
 Auto-Tag Cross-Seeds with hash and let it be used as a variable

### ISSUE THREAD

**Issue by zenxedo** [StuffAnThings/qbit_manage#699]
### Is your feature request related to a problem? Please elaborate.

Cross-seeding can sometimes lead to an endless loop of torrent additions, especially when multiple trackers are cross-seeding the same content. Managing this behavior currently requires setting a high excludeOlder or excludeRecentSearch time, which is not ideal for all workflows. 

If this feature were implemented, users could designate a preferred tracker that automatically removes all associated cross-seeds from other trackers. This would allow for seamless prioritization of desired trackers while cleaning up redundant cross-seeds in a single action, eliminating the need for manual intervention or overly complex exclude settings.

### Describe the solution you'd like

Auto-Tagging Option: Automatically assign tags in the format cross-seed-{hash} to cross-seeded torrents. This allows precise tracking and removal of cross-seeds when necessary.

Database Integration (Preferred Option): Instead of creating tags directly in qBittorrent, store these tags in a lightweight external database. The database would maintain the association between the torrent hash and its cross-seed status. This avoids cluttering the qBittorrent interface while retaining functionality.

Then you can call it using {hash} as a variable
match_any:
        - tags: cross-seed-{hash}

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

Using qBittorrent’s Native Tagging Manually
Setting High Exclude Times in Cross-Seed
Creating two custom scripts tailored to automate tagging and deletion

### Who will this benefit?

This will benefit cross-seed users who want full automation and control of when cross-seeds are removed based on there preferred tracker. It has been brought up many times before about the cross-seeds getting recrossed in a loop.

### Additional Information

Maybe there is a better solution to this or one that I overlooked

**Comment by bakerboy448** [comment]
QBm is not responsible for figuring out xseed's issues

Additionally this would result in hundreds or thousands of tags which is not sustainable
