### ISSUE TITLE
[FR] Automatically detect unregistered torrents in BHD

### ISSUE THREAD

**Issue by bobokun** [StuffAnThings/qbit_manage#70]
Use BHD API to detect unregistered torrents since the tracker status is not consistent when a torrent is deleted.

**Comment by muddro1** [comment]
I don't think this is currently working properly in that it is not detecting the unregistered torrents.

**Comment by Drazzilb08** [comment]
Can you please provide examples? Maybe screenshots of the tracker message from qB.

**Comment by muddro1** [comment]
![image](https://user-images.githubusercontent.com/15880479/148397641-9997e739-ff93-4b06-af9b-70a4c6b98863.png)

**Comment by Drazzilb08** [comment]
Strange, that one I know for a fact is one we've covered before integration. 
What version are you running? 
Does it even come up as an issue (a new category w/in qB)?
Can you double-check the API key is the correct one?
Can you run qb in `DEBUG` mode and see if anything comes from the logs about that particular torrent?

**Comment by muddro1** [comment]
using Hotio's 4.3.9 container for qbit (qflood container to be exact)
its not coming up as an issue
