### ISSUE TITLE
[FR]: About share_limits_min_seeding_time_tag

### ISSUE THREAD

**Issue by TheRealBix** [StuffAnThings/qbit_manage#700]
### Is your feature request related to a problem? Please elaborate.

Right now, a share limited torrent needs two criteria to be tagged with _share_limits_min_seeding_time_tag_ : 
- torrent seed time < _min_seeding_time_
- torrent ratio > _max_ratio_

Why the latter ? 

### Describe the solution you'd like

Be allowed to set _max_ratio_ to zero or, better, just not make it a criteria for _share_limits_min_seeding_time_tag_

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Setting max_ratio to zero is not allowed, so I set it to 0.0001 or something but there always are some torrent that stay to 0 byte uploaded so ratio will never be positive.

### Who will this benefit?

Anyone who wants to manage torrents with seeding time and not ratio.

**Comment by bakerboy448** [comment]
Please read the docs that explain max seed time, max ratio, and min seed time.

Min seed time has no relevance to a seed time goal.

Seed time goals are already supported

**Comment by TheRealBix** [comment]
Maybe I wasn't clear enough, my english is limited, or I just don't understand your doc...
We agree "Minimum seeding time" is _min_seeding_time_ ?

> _share_limits_min_seeding_time_tag_ : Will add this tag when applying share limits to torrents that have not yet reached the minimum seeding time (Used in --share-limits)

yet this is not the case when a torrent ratio is below _max_ratio_

**Comment by bakerboy448** [comment]
Why is max seeding time unable to do exactly what you want?

**Comment by TheRealBix** [comment]
Oh but I was actually using _max_seeding_time_ at first, but the aforementioned tag isn't applied either while this seeding time isn't reached.

**Comment by bakerboy448** [comment]
Correct. The min seeding time tag will never ever be applied for max seeding time.  There is no tag to set nor does it make sense to set a tag if a torrent has not met max ratio or max seedtime....
