### ISSUE TITLE
[FR] - cross seed - Apply seed time and ratio limits based on original torrent

### ISSUE THREAD

**Issue by afraazali** [StuffAnThings/qbit_manage#71]
For my permaseed torrents, I like to set the share ratio to **Set no share limit** so they don't stop/pause seeding. I'd like to have the `cross_seed` function use the original torrent's `seeding_time_limit` and `ratio_limit` properties. It looks like the library that this script uses provides the ability to do so:

https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_add

**Comment by bobokun** [comment]
Just to be clear, you mean the `max_seeding_time` . `max_ratio`. and `limit_upload_speed` that's defined in the `tracker` (previously known as `tag`) section  in the config right?

**Comment by afraazali** [comment]
That’s correct. Is it already possible and I just missed it in the configs?

**Comment by bobokun** [comment]
Well currently it would add the cross seed torrent, then on the second run of qbit_manage using the `tag_update` function  it would add the appropriate tracker tag and limits so depending on how often you run it then it would get handled in the second run

**Comment by afraazali** [comment]
Ah ok, that won’t work for my use case. I’ll see if I can make some changes to handle my use case.

**Comment by bobokun** [comment]
Hm so just so im clear you want cross seed torrent to have the same share limits as the original torrent despite being on a different tracker?

**Comment by afraazali** [comment]
That’s correct. So the way I do torrents, I have qbit set to seed for 15 days for movies and tv. This is way more than even my strictest tracker. There are times where I want to keep things, so I manually go in, disable the share/ratio limit and re-categorize to the “permaseed” category. When cross seeds come in for any torrent, even permaseed, currently they follow the global limit, 15 days. I go in and manually change that for any cross seeds that are added for permaseeds. Now that I explain it, I can see this _may_ be a very niche use case. I’ve implemented something for the time being, so I’ll have to test and see when a permaseed cross seed comes in.
