### ISSUE TITLE
[FR]: Tag torrents which have a tracker issue.

### ISSUE THREAD

**Issue by onedr0p** [StuffAnThings/qbit_manage#91]
### Is your feature request related to a problem? Please elaborate.

I maintain a script that does this but was wondering if this project could support the feature.

https://github.com/k8s-at-home/qbittorrent-scripts

Thanks!

### Describe the solution you'd like

Unregistered torrents on trackers are hard to find in the UI. It would be nice to have those be tagged or optionally deleted.

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

N/A

### Who will this benefit?

Anyone that uses trackers that delete their torrents when a media file is bad or upgraded.

**Comment by bobokun** [comment]
Is there something your script does qbit_manage doesn't do? It can already remove unregistered torrents and tag any potential issue torrents using the command `--rem-unregistered`. See full list of [Commands](https://github.com/StuffAnThings/qbit_manage/wiki/Commands) that qbit_manage can do.

**Comment by bobokun** [comment]
No it will only remove unregistered if any of the error messages are covered by the any of the keywords set:
https://github.com/StuffAnThings/qbit_manage/blob/393538acf52d6081ea519eefcdb387734c1dd975/modules/qbittorrent.py#L443-L452

Anything that has an error that is not covered by those keywords will be tagged as `issue` for manual review. If you find any unregistered torrents that are tagged as issue you can create a feature request and I can add it to the list

**Comment by onedr0p** [comment]
Ohhh! Got it thanks I guess maybe this feature request would be to tag them `issue` instead of deleting them then.

**Comment by bobokun** [comment]
sure, that shouldn't be an issue

**Comment by bobokun** [comment]
Use `--tag-tracker-error` or docker env variable `QBT_TAG_TRACKER_ERROR` to tag them. In the config you can specify what the tag is under the `settings` parent attribute using the `tracker_error_tag` subattribute. See the updated config.yml.sample in develop

**Comment by onedr0p** [comment]
Woah thanks!
