### ISSUE TITLE
[FR]: Tag Torrents With Trackers That Don't Match Any Configured Trackers

### ISSUE THREAD

**Issue by HarryMuscle** [StuffAnThings/qbit_manage#96]
### Is your feature request related to a problem? Please elaborate.

It would be useful to be able to control public torrents and their ratio and seeding time via qbit-torrent.

### Describe the solution you'd like

Add a "Public Tracker" or maybe "Other Tracker" tag with associated ratio and seeding time settings.  Basically it would be a tag added to torrents that don't have a tracker that matches any other configured trackers.  Assuming you configured all of the private trackers you use then this would tag public torrents which would allow setting the ratio and seeding time for public torrents via qbit-manage.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

None yet

### Who will this benefit?

Anyone who uses private and public torrents.

**Comment by bobokun** [comment]
Currently if a tracker isn't configured it will add the trackers that are missing in your config.yml file when trying to tag.

**Comment by HarryMuscle** [comment]
> Currently if a tracker isn't configured it will add the trackers that are missing in your config.yml file when trying to tag.

That sounds like a good idea for private trackers but I can see this becoming difficult to manage for those that use public trackers since there are so many and they come and go over time.  Ideally I think there should be an option to either keep the existing functionality (for those that use private trackers) and an option to simply tag torrents with trackers not found in the config as "Public Torrent" or "Other Tracker" and have a single ratio and time setting for those, instead of having to manage dozens upon dozens of public trackers individually and having to continually keep the config updated as those trackers come and go.

**Comment by bobokun** [comment]
How would you identify the torrent is public or private?

**Comment by HarryMuscle** [comment]
> How would you identify the torrent is public or private?

If the tracker is in the configuration file it's save to assume it's a private tracker you configured.  If the tracker isn't in the configuration file then assume it's public.  Alternatively instead of calling the tag "Public Tracker" or "Public Torrent" play it safe and just call it "Other Tracker".

**Comment by bobokun** [comment]
I don't think we can safely assume that if it's not in the configuration file then it's public.

**Comment by HarryMuscle** [comment]
> I don't think we can safely assume that if it's not in the configuration file then it's public.

That's fair.  The suggested feature would still be useful though.  Just use the "Other Tracker" terminology instead of using the term "Public".

**Comment by bobokun** [comment]
I'll see if I can come up with a solution.

**Comment by firestrife23** [comment]
following this one, because most of public stuffs doesn't get processed unless it's coming from private tracker. Most of my *arr containers would add tags like "sonarr", "radarr", "readarr", and etc... would it be possible to process those tags instead of tracker?

**Comment by bakerboy448** [comment]
\*arrs cannot add tags - they use categories.

**Comment by firestrife23** [comment]
you're right, that's what I meant by mentoring the categories type set by 3rd party applications.

**Comment by bjeanes** [comment]
> How would you identify the torrent is public or private?

qB knows if they are private because of the private flag in the metainfo.

<img width="833" alt="Screen Shot 2022-09-17 at 2 01 38 pm" src="https://user-images.githubusercontent.com/2560/190839746-28bd424d-2448-4d00-83af-a896f8d34306.png">

It's how qB and other clients know to disable DHT et al.

I also want this feature or at least a variant of it which allows me to tag "public" or "private" on all torrents based on tracker privacy (because qB WebUI annoyingly doesn't have a view for all private torrents). Further, it would let me drop https://github.com/Hundter/qBittorrent-Ratio-Manager which I use to set general ratio rules for private vs public trackers (it doesn't actually set them in qB, it just removes the torrents and data when the configured ratio cons.traints are met)

**Comment by bobokun** [comment]
The latest develop branch adds support for this. In order to use it just update to develop and add the following `other` keyword under trackers config.

Example:
```yaml
tracker:
  other:
    tag: public
    max_ratio: 10.0
    max_seeding_time: 120000
    limit_upload_speed: 150
```
