### ISSUE TITLE
[FR]: Add option for cleanup of dead seeds

### ISSUE THREAD

**Issue by theimmortal68** [StuffAnThings/qbit_manage#98]
### Is your feature request related to a problem? Please elaborate.

I usually remove seeds that have been inactive for an extended period of time.

### Describe the solution you'd like

Add an option to tag/remove inactive torrents with an option to set a threshold for inactivity. For example, allow an option in the config to set a 90-day threshold and have the script tag/remove any torrents that have been inactive for 90+ days.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I have not found any way other than manually sorting through the torrents.

### Who will this benefit?

Anyone who likes to seed as long as possible but has limited hard drive space to keep inactive torrents indefinitely.

**Comment by bakerboy448** [comment]
This should be accomplishanblr with max seed time and last active + min seeds
