### ISSUE TITLE
[FR]: New reasons for "issue" tag, possible attention needed

### ISSUE THREAD

**Issue by ahatdude** [StuffAnThings/qbit_manage#99]
### Is your feature request related to a problem? Please elaborate.

Firstly, I will admit that recently I had some issues due to my own mistakes and ended up deleting a large part of my seeding torrents. To remedy this I restored most of the files by going into the recycle bin as well as the orphaned folder.

All of my library is now restored, but by doing that I had also added many files that were truly orphaned due to radarr/sonarr finding better versions.  I expected qbM to fix this, as it had in the first place and it mostly did. However a new problem arose and a few of my torrents are now tagged with "issue".

These are the 3 errors I have found:

1. **401: You cannot download or seed the same torrents from more than 3 locations**

Torrent name: _Alone.S02.1080p.AMZN.WEB-DL.DD+2.0.x264-Cinefeel_

From what I gather looking at qBittorrent, there are indeed 4 torrents all seeding the same file. Is this a limitation imposed by qBittorrent or by the tracker? If it is by the tracker, would it be possible to add a feature to prioritise trackers? If I may suggest, it would be nice if it worked as such: 

> original tracker > pre-configured tracker 1 > pre-configured tracker 2 etc etc

2. **You have reached the client limit for this torrent**

Torrent name: _A.Beautiful.Planet.2016.BluRay.Remux.1080p.AVC.DTS.X.7.1-BMF.mkv_

Looking at qBittorrent I can see that this torrent also has 4 torrents, one of them with this issue, another with the first one I mentioned, and another that has its status as "not contacted yet". The original one is fine.

3. **Sorry max peers reached! Redownload torrent from https://hd-torrents.org**

Torrent name: _Hawkeye.2021.S01E02.Hide.and.Seek.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-TEPES.mkv_

I have 2 torrents with this name. One is working fine. Both are tagged with noHL AND cross-seed.

I have zipped up the latest logs to try and give you an understanding of what is happening.

Thank you for your help.

[activity.log.zip](https://github.com/StuffAnThings/qbit_manage/files/7910606/activity.log.zip)

### Describe the solution you'd like

Hopefully to understand what the errors are and if they are fixable to find a solution.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I have considered deleting all those affected torrents, but I think that it's important to find all these issues and document them.

### Who will this benefit?

Everyone that comes across these issues.

**Comment by bakerboy448** [comment]
pretty sure those are all messages from your trackers and have nothing to do with qbitmanage

**Comment by ahatdude** [comment]
It is possible. After around 12-14hours the number of torrents with the issue tag has dropped to 34, so in the next hours maybe it'll completely disappear. 
I'll keep you updated and close the ticket if it is the case.

**Comment by bobokun** [comment]
> The only issue present is error number 3.
> > Sorry max peers reached! Redownload torrent from https://hd-torrents.org

This seems like a valid issue. It's clear from the message that you should redownload the torrent. Try doing that and see if the error will go away.

**Comment by ahatdude** [comment]
To conclude this ticket, I'll just leave here what I did for any future user that runs into this problem:

I let the script run a few more times and a few more movies somehow fixed themselves.I wonder if ultimately these errors would drop off with time (at least some of them), but personally I just deleted the noHL torrents torrents and redownloaded the other ones.

Thank you.
